// Copyright © 2023 Cisco Systems, Inc. and its affiliates.
// All rights reserved.
//
// Licensed under the Mozilla Public License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://mozilla.org/MPL/2.0/
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// SPDX-License-Identifier: MPL-2.0

// Code generated by "gen/generator.go"; DO NOT EDIT.

package provider

import (
	"context"
	"fmt"

	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-log/tflog"
	"github.com/netascode/go-restconf"
)

// Ensure the implementation satisfies the expected interfaces.
var (
	_ datasource.DataSource              = &GlobalSettingsDataSource{}
	_ datasource.DataSourceWithConfigure = &GlobalSettingsDataSource{}
)

func NewGlobalSettingsDataSource() datasource.DataSource {
	return &GlobalSettingsDataSource{}
}

type GlobalSettingsDataSource struct {
	clients map[string]*restconf.Client
}

func (d *GlobalSettingsDataSource) Metadata(_ context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_global_settings"
}

func (d *GlobalSettingsDataSource) Schema(ctx context.Context, req datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	resp.Schema = schema.Schema{
		// This description is used by the documentation generator and the language server.
		MarkdownDescription: "This data source can read the Global Settings configuration.",

		Attributes: map[string]schema.Attribute{
			"instance": schema.StringAttribute{
				MarkdownDescription: "An instance name from the provider configuration.",
				Optional:            true,
			},
			"id": schema.StringAttribute{
				MarkdownDescription: "The RESTCONF path.",
				Computed:            true,
			},
			"connect_timeout": schema.Int64Attribute{
				MarkdownDescription: "Timeout in seconds for new connections.",
				Computed:            true,
			},
			"read_timeout": schema.Int64Attribute{
				MarkdownDescription: "Timeout in seconds used when reading data.",
				Computed:            true,
			},
			"write_timeout": schema.Int64Attribute{
				MarkdownDescription: "Timeout in seconds used when writing data.",
				Computed:            true,
			},
			"no_wait_for_lock": schema.BoolAttribute{
				MarkdownDescription: "Do not wait for the device lock, fail immediately.",
				Computed:            true,
			},
			"wait_for_lock_timeout": schema.Int64Attribute{
				MarkdownDescription: "Timeout in seconds to wait for device lock.",
				Computed:            true,
			},
			"wait_for_lock_infinity": schema.BoolAttribute{
				MarkdownDescription: "Wait indefinitely for the device lock.",
				Computed:            true,
			},
			"ssh_keep_alive_interval": schema.Int64Attribute{
				MarkdownDescription: "The SSH keep alive interval in seconds.",
				Computed:            true,
			},
			"ssh_keep_alive_count": schema.Int64Attribute{
				MarkdownDescription: "The number of SSH keep alive messages before disconnect.",
				Computed:            true,
			},
			"ssh_algorithms_public_key": schema.ListAttribute{
				MarkdownDescription: "A list of SSH public key algorithms.",
				ElementType:         types.StringType,
				Computed:            true,
			},
			"ssh_algorithms_kex": schema.ListAttribute{
				MarkdownDescription: "A list of SSH key exchange algorithms.",
				ElementType:         types.StringType,
				Computed:            true,
			},
			"ssh_algorithms_mac": schema.ListAttribute{
				MarkdownDescription: "A list of SSH MAC algorithms.",
				ElementType:         types.StringType,
				Computed:            true,
			},
			"ssh_algorithms_cipher": schema.ListAttribute{
				MarkdownDescription: "A list of SSH cipher algorithms.",
				ElementType:         types.StringType,
				Computed:            true,
			},
			"ssh_algorithms_compression": schema.ListAttribute{
				MarkdownDescription: "A list of SSH compression algorithms.",
				ElementType:         types.StringType,
				Computed:            true,
			},
			"ssh_algorithms_dh_group_min_size": schema.Int64Attribute{
				MarkdownDescription: "Minimum size of the DH group.",
				Computed:            true,
			},
			"ssh_algorithms_dh_group_preferred_size": schema.Int64Attribute{
				MarkdownDescription: "Preferred size of the DH group.",
				Computed:            true,
			},
			"ssh_algorithms_dh_group_max_size": schema.Int64Attribute{
				MarkdownDescription: "Maximum size of the DH group.",
				Computed:            true,
			},
			"ned_keep_alive_interval": schema.Int64Attribute{
				MarkdownDescription: "The NED keep alive interval in seconds.",
				Computed:            true,
			},
			"ned_keep_alive_count": schema.Int64Attribute{
				MarkdownDescription: "The number of NED keep alive messages before disconnect.",
				Computed:            true,
			},
			"connect_retries_attempts": schema.Int64Attribute{
				MarkdownDescription: "Number of connection retry attempts.",
				Computed:            true,
			},
			"connect_retries_timeout": schema.Int64Attribute{
				MarkdownDescription: "Timeout in seconds between connection retry attempts.",
				Computed:            true,
			},
			"trace": schema.StringAttribute{
				MarkdownDescription: "Trace output control.",
				Computed:            true,
			},
			"trace_output": schema.StringAttribute{
				MarkdownDescription: "Where to send trace output.",
				Computed:            true,
			},
			"ned_settings_use_confirmed_commit": schema.BoolAttribute{
				MarkdownDescription: "Use confirmed commit toward the device.",
				Computed:            true,
			},
			"ned_settings_use_validate": schema.BoolAttribute{
				MarkdownDescription: "Use validate toward the device.",
				Computed:            true,
			},
			"ned_settings_use_startup": schema.BoolAttribute{
				MarkdownDescription: "Use startup datastore toward the device.",
				Computed:            true,
			},
			"ned_settings_use_transaction_id": schema.BoolAttribute{
				MarkdownDescription: "Use transaction ID toward the device.",
				Computed:            true,
			},
			"ned_settings_use_private_candidate": schema.BoolAttribute{
				MarkdownDescription: "Use private candidate datastore toward the device.",
				Computed:            true,
			},
			"ned_settings_use_junos_rollback": schema.BoolAttribute{
				MarkdownDescription: "Use Junos rollback mechanism.",
				Computed:            true,
			},
			"no_overwrite_enabled_by_default": schema.BoolAttribute{
				MarkdownDescription: "Enable no-overwrite by default.",
				Computed:            true,
			},
			"no_overwrite_compare": schema.StringAttribute{
				MarkdownDescription: "No-overwrite comparison method.",
				Computed:            true,
			},
			"lsa_no_overwrite_enabled_by_default": schema.BoolAttribute{
				MarkdownDescription: "Enable LSA no-overwrite by default.",
				Computed:            true,
			},
			"lsa_no_overwrite_compare": schema.StringAttribute{
				MarkdownDescription: "LSA no-overwrite comparison method.",
				Computed:            true,
			},
			"out_of_sync_commit_behaviour": schema.StringAttribute{
				MarkdownDescription: "How to handle out-of-sync devices during commit.",
				Computed:            true,
			},
			"use_lsa": schema.BoolAttribute{
				MarkdownDescription: "Use LSA (Layered Service Architecture).",
				Computed:            true,
			},
			"no_lsa": schema.BoolAttribute{
				MarkdownDescription: "Disable LSA.",
				Computed:            true,
			},
			"session_limits_max_sessions": schema.Int64Attribute{
				MarkdownDescription: "Maximum number of concurrent sessions.",
				Computed:            true,
			},
			"session_limits_connect_rate_burst": schema.Int64Attribute{
				MarkdownDescription: "Maximum burst of connections allowed.",
				Computed:            true,
			},
			"session_limits_max_wait_time": schema.Int64Attribute{
				MarkdownDescription: "Maximum time in seconds to wait for a session.",
				Computed:            true,
			},
			"session_pool_max_sessions": schema.Int64Attribute{
				MarkdownDescription: "Maximum number of pooled sessions.",
				Computed:            true,
			},
			"session_pool_idle_time": schema.Int64Attribute{
				MarkdownDescription: "Idle time in seconds before a pooled session is closed.",
				Computed:            true,
			},
			"session_pool_pool_max_sessions": schema.Int64Attribute{
				MarkdownDescription: "Maximum number of sessions in the connection pool.",
				Computed:            true,
			},
			"commit_queue_enabled_by_default": schema.BoolAttribute{
				MarkdownDescription: "Enable commit queue by default.",
				Computed:            true,
			},
			"commit_queue_atomic": schema.BoolAttribute{
				MarkdownDescription: "Whether commit queue operations are atomic.",
				Computed:            true,
			},
			"commit_queue_retry_attempts": schema.Int64Attribute{
				MarkdownDescription: "Number of commit queue retry attempts.",
				Computed:            true,
			},
			"commit_queue_retry_timeout": schema.Int64Attribute{
				MarkdownDescription: "Timeout in seconds between commit queue retry attempts.",
				Computed:            true,
			},
			"commit_queue_error_option": schema.StringAttribute{
				MarkdownDescription: "Commit queue error handling option.",
				Computed:            true,
			},
			"commit_retries_attempts": schema.Int64Attribute{
				MarkdownDescription: "Number of commit retry attempts.",
				Computed:            true,
			},
			"commit_retries_timeout": schema.Int64Attribute{
				MarkdownDescription: "Timeout in seconds between commit retry attempts.",
				Computed:            true,
			},
			"trace_dir": schema.StringAttribute{
				MarkdownDescription: "The directory for trace output files.",
				Computed:            true,
			},
			"report_multiple_errors": schema.BoolAttribute{
				MarkdownDescription: "Report multiple errors.",
				Computed:            true,
			},
		},
	}
}

func (d *GlobalSettingsDataSource) Configure(_ context.Context, req datasource.ConfigureRequest, _ *datasource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}

	d.clients = req.ProviderData.(map[string]*restconf.Client)
}

func (d *GlobalSettingsDataSource) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
	var config GlobalSettingsData

	// Read config
	diags := req.Config.Get(ctx, &config)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}

	if _, ok := d.clients[config.Instance.ValueString()]; !ok {
		resp.Diagnostics.AddAttributeError(path.Root("instance"), "Invalid instance", fmt.Sprintf("Instance '%s' does not exist in provider configuration.", config.Instance.ValueString()))
		return
	}

	tflog.Debug(ctx, fmt.Sprintf("%s: Beginning Read", config.getPath()))

	res, err := d.clients[config.Instance.ValueString()].GetData(config.getPath(), restconf.Query("content", "config"))
	if res.StatusCode == 404 {
		config = GlobalSettingsData{Instance: config.Instance}
	} else {
		if err != nil {
			resp.Diagnostics.AddError("Client Error", fmt.Sprintf("Failed to retrieve object, got error: %s", err))
			return
		}

		config.fromBody(ctx, res.Res)
	}

	config.Id = types.StringValue(config.getPath())

	tflog.Debug(ctx, fmt.Sprintf("%s: Read finished successfully", config.getPath()))

	diags = resp.State.Set(ctx, &config)
	resp.Diagnostics.Append(diags...)
}
