// Copyright © 2023 Cisco Systems, Inc. and its affiliates.
// All rights reserved.
//
// Licensed under the Mozilla Public License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://mozilla.org/MPL/2.0/
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// SPDX-License-Identifier: MPL-2.0

// Code generated by "gen/generator.go"; DO NOT EDIT.

package provider

import (
	"context"
	"fmt"
	"net/url"
	"regexp"
	"strconv"

	"github.com/CiscoDevNet/terraform-provider-nso/internal/provider/helpers"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/tidwall/gjson"
	"github.com/tidwall/sjson"
)

type DeviceGroup struct {
	Instance          types.String `tfsdk:"instance"`
	Id                types.String `tfsdk:"id"`
	Name              types.String `tfsdk:"name"`
	DeviceNames       types.List   `tfsdk:"device_names"`
	DeviceGroups      types.List   `tfsdk:"device_groups"`
	LocationName      types.String `tfsdk:"location_name"`
	LocationLatitude  types.String `tfsdk:"location_latitude"`
	LocationLongitude types.String `tfsdk:"location_longitude"`
	LocationAltitude  types.Int64  `tfsdk:"location_altitude"`
}

type DeviceGroupData struct {
	Instance          types.String `tfsdk:"instance"`
	Id                types.String `tfsdk:"id"`
	Name              types.String `tfsdk:"name"`
	DeviceNames       types.List   `tfsdk:"device_names"`
	DeviceGroups      types.List   `tfsdk:"device_groups"`
	LocationName      types.String `tfsdk:"location_name"`
	LocationLatitude  types.String `tfsdk:"location_latitude"`
	LocationLongitude types.String `tfsdk:"location_longitude"`
	LocationAltitude  types.Int64  `tfsdk:"location_altitude"`
}

func (data DeviceGroup) getPath() string {
	return fmt.Sprintf("tailf-ncs:devices/device-group=%v", url.QueryEscape(fmt.Sprintf("%v", data.Name.ValueString())))
}

func (data DeviceGroupData) getPath() string {
	return fmt.Sprintf("tailf-ncs:devices/device-group=%v", url.QueryEscape(fmt.Sprintf("%v", data.Name.ValueString())))
}

// if last path element has a key -> remove it
func (data DeviceGroup) getPathShort() string {
	path := data.getPath()
	re := regexp.MustCompile(`(.*)=[^\/]*$`)
	matches := re.FindStringSubmatch(path)
	if len(matches) <= 1 {
		return path
	}
	return matches[1]
}

func (data DeviceGroup) toBody(ctx context.Context) string {
	body := `{"` + helpers.LastElement(data.getPath()) + `":{}}`
	if !data.Name.IsNull() && !data.Name.IsUnknown() {
		body, _ = sjson.Set(body, helpers.LastElement(data.getPath())+"."+"name", data.Name.ValueString())
	}
	if !data.DeviceNames.IsNull() && !data.DeviceNames.IsUnknown() {
		var values []string
		data.DeviceNames.ElementsAs(ctx, &values, false)
		body, _ = sjson.Set(body, helpers.LastElement(data.getPath())+"."+"device-name", values)
	}
	if !data.DeviceGroups.IsNull() && !data.DeviceGroups.IsUnknown() {
		var values []string
		data.DeviceGroups.ElementsAs(ctx, &values, false)
		body, _ = sjson.Set(body, helpers.LastElement(data.getPath())+"."+"device-group", values)
	}
	if !data.LocationName.IsNull() && !data.LocationName.IsUnknown() {
		body, _ = sjson.Set(body, helpers.LastElement(data.getPath())+"."+"location.name", data.LocationName.ValueString())
	}
	if !data.LocationLatitude.IsNull() && !data.LocationLatitude.IsUnknown() {
		body, _ = sjson.Set(body, helpers.LastElement(data.getPath())+"."+"location.latitude", data.LocationLatitude.ValueString())
	}
	if !data.LocationLongitude.IsNull() && !data.LocationLongitude.IsUnknown() {
		body, _ = sjson.Set(body, helpers.LastElement(data.getPath())+"."+"location.longitude", data.LocationLongitude.ValueString())
	}
	if !data.LocationAltitude.IsNull() && !data.LocationAltitude.IsUnknown() {
		body, _ = sjson.Set(body, helpers.LastElement(data.getPath())+"."+"location.altitude", strconv.FormatInt(data.LocationAltitude.ValueInt64(), 10))
	}
	return body
}

func (data *DeviceGroup) updateFromBody(ctx context.Context, res gjson.Result) {
	prefix := helpers.LastElement(data.getPath()) + "."
	if res.Get(helpers.LastElement(data.getPath())).IsArray() {
		prefix += "0."
	}
	if value := res.Get(prefix + "name"); value.Exists() && !data.Name.IsNull() {
		data.Name = types.StringValue(value.String())
	} else {
		data.Name = types.StringNull()
	}
	if value := res.Get(prefix + "device-name"); value.Exists() && !data.DeviceNames.IsNull() {
		data.DeviceNames = helpers.GetStringList(value.Array())
	} else {
		data.DeviceNames = types.ListNull(types.StringType)
	}
	if value := res.Get(prefix + "device-group"); value.Exists() && !data.DeviceGroups.IsNull() {
		data.DeviceGroups = helpers.GetStringList(value.Array())
	} else {
		data.DeviceGroups = types.ListNull(types.StringType)
	}
	if value := res.Get(prefix + "location.name"); value.Exists() && !data.LocationName.IsNull() {
		data.LocationName = types.StringValue(value.String())
	} else {
		data.LocationName = types.StringNull()
	}
	if value := res.Get(prefix + "location.latitude"); value.Exists() && !data.LocationLatitude.IsNull() {
		data.LocationLatitude = types.StringValue(value.String())
	} else {
		data.LocationLatitude = types.StringNull()
	}
	if value := res.Get(prefix + "location.longitude"); value.Exists() && !data.LocationLongitude.IsNull() {
		data.LocationLongitude = types.StringValue(value.String())
	} else {
		data.LocationLongitude = types.StringNull()
	}
	if value := res.Get(prefix + "location.altitude"); value.Exists() && !data.LocationAltitude.IsNull() {
		data.LocationAltitude = types.Int64Value(value.Int())
	} else {
		data.LocationAltitude = types.Int64Null()
	}
}

func (data *DeviceGroupData) fromBody(ctx context.Context, res gjson.Result) {
	prefix := helpers.LastElement(data.getPath()) + "."
	if res.Get(helpers.LastElement(data.getPath())).IsArray() {
		prefix += "0."
	}
	if value := res.Get(prefix + "device-name"); value.Exists() {
		data.DeviceNames = helpers.GetStringList(value.Array())
	} else {
		data.DeviceNames = types.ListNull(types.StringType)
	}
	if value := res.Get(prefix + "device-group"); value.Exists() {
		data.DeviceGroups = helpers.GetStringList(value.Array())
	} else {
		data.DeviceGroups = types.ListNull(types.StringType)
	}
	if value := res.Get(prefix + "location.name"); value.Exists() {
		data.LocationName = types.StringValue(value.String())
	}
	if value := res.Get(prefix + "location.latitude"); value.Exists() {
		data.LocationLatitude = types.StringValue(value.String())
	}
	if value := res.Get(prefix + "location.longitude"); value.Exists() {
		data.LocationLongitude = types.StringValue(value.String())
	}
	if value := res.Get(prefix + "location.altitude"); value.Exists() {
		data.LocationAltitude = types.Int64Value(value.Int())
	}
}

func (data *DeviceGroup) getDeletedListItems(ctx context.Context, state DeviceGroup) []string {
	deletedListItems := make([]string, 0)
	return deletedListItems
}

func (data *DeviceGroup) getEmptyLeafsDelete(ctx context.Context) []string {
	emptyLeafsDelete := make([]string, 0)
	return emptyLeafsDelete
}

func (data *DeviceGroup) getDeletePaths(ctx context.Context) []string {
	var deletePaths []string
	if !data.DeviceNames.IsNull() {
		deletePaths = append(deletePaths, fmt.Sprintf("%v/device-name", data.getPath()))
	}
	if !data.DeviceGroups.IsNull() {
		deletePaths = append(deletePaths, fmt.Sprintf("%v/device-group", data.getPath()))
	}
	if !data.LocationName.IsNull() {
		deletePaths = append(deletePaths, fmt.Sprintf("%v/location/name", data.getPath()))
	}
	if !data.LocationLatitude.IsNull() {
		deletePaths = append(deletePaths, fmt.Sprintf("%v/location/latitude", data.getPath()))
	}
	if !data.LocationLongitude.IsNull() {
		deletePaths = append(deletePaths, fmt.Sprintf("%v/location/longitude", data.getPath()))
	}
	if !data.LocationAltitude.IsNull() {
		deletePaths = append(deletePaths, fmt.Sprintf("%v/location/altitude", data.getPath()))
	}
	return deletePaths
}
