// Copyright © 2023 Cisco Systems, Inc. and its affiliates.
// All rights reserved.
//
// Licensed under the Mozilla Public License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://mozilla.org/MPL/2.0/
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// SPDX-License-Identifier: MPL-2.0

// Code generated by "gen/generator.go"; DO NOT EDIT.

package provider

import (
	"context"
	"fmt"
	"regexp"
	"strconv"

	"github.com/CiscoDevNet/terraform-provider-nso/internal/provider/helpers"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/tidwall/gjson"
	"github.com/tidwall/sjson"
)

type GlobalSettings struct {
	Instance                          types.String `tfsdk:"instance"`
	Id                                types.String `tfsdk:"id"`
	ConnectTimeout                    types.Int64  `tfsdk:"connect_timeout"`
	ReadTimeout                       types.Int64  `tfsdk:"read_timeout"`
	WriteTimeout                      types.Int64  `tfsdk:"write_timeout"`
	NoWaitForLock                     types.Bool   `tfsdk:"no_wait_for_lock"`
	WaitForLockTimeout                types.Int64  `tfsdk:"wait_for_lock_timeout"`
	WaitForLockInfinity               types.Bool   `tfsdk:"wait_for_lock_infinity"`
	SshKeepAliveInterval              types.Int64  `tfsdk:"ssh_keep_alive_interval"`
	SshKeepAliveCount                 types.Int64  `tfsdk:"ssh_keep_alive_count"`
	SshAlgorithmsPublicKey            types.List   `tfsdk:"ssh_algorithms_public_key"`
	SshAlgorithmsKex                  types.List   `tfsdk:"ssh_algorithms_kex"`
	SshAlgorithmsMac                  types.List   `tfsdk:"ssh_algorithms_mac"`
	SshAlgorithmsCipher               types.List   `tfsdk:"ssh_algorithms_cipher"`
	SshAlgorithmsCompression          types.List   `tfsdk:"ssh_algorithms_compression"`
	SshAlgorithmsDhGroupMinSize       types.Int64  `tfsdk:"ssh_algorithms_dh_group_min_size"`
	SshAlgorithmsDhGroupPreferredSize types.Int64  `tfsdk:"ssh_algorithms_dh_group_preferred_size"`
	SshAlgorithmsDhGroupMaxSize       types.Int64  `tfsdk:"ssh_algorithms_dh_group_max_size"`
	NedKeepAliveInterval              types.Int64  `tfsdk:"ned_keep_alive_interval"`
	NedKeepAliveCount                 types.Int64  `tfsdk:"ned_keep_alive_count"`
	ConnectRetriesAttempts            types.Int64  `tfsdk:"connect_retries_attempts"`
	ConnectRetriesTimeout             types.Int64  `tfsdk:"connect_retries_timeout"`
	Trace                             types.String `tfsdk:"trace"`
	TraceOutput                       types.String `tfsdk:"trace_output"`
	NedSettingsUseConfirmedCommit     types.Bool   `tfsdk:"ned_settings_use_confirmed_commit"`
	NedSettingsUseValidate            types.Bool   `tfsdk:"ned_settings_use_validate"`
	NedSettingsUseStartup             types.Bool   `tfsdk:"ned_settings_use_startup"`
	NedSettingsUseTransactionId       types.Bool   `tfsdk:"ned_settings_use_transaction_id"`
	NedSettingsUsePrivateCandidate    types.Bool   `tfsdk:"ned_settings_use_private_candidate"`
	NedSettingsUseJunosRollback       types.Bool   `tfsdk:"ned_settings_use_junos_rollback"`
	NoOverwriteEnabledByDefault       types.Bool   `tfsdk:"no_overwrite_enabled_by_default"`
	NoOverwriteCompare                types.String `tfsdk:"no_overwrite_compare"`
	LsaNoOverwriteEnabledByDefault    types.Bool   `tfsdk:"lsa_no_overwrite_enabled_by_default"`
	LsaNoOverwriteCompare             types.String `tfsdk:"lsa_no_overwrite_compare"`
	OutOfSyncCommitBehaviour          types.String `tfsdk:"out_of_sync_commit_behaviour"`
	UseLsa                            types.Bool   `tfsdk:"use_lsa"`
	NoLsa                             types.Bool   `tfsdk:"no_lsa"`
	SessionLimitsMaxSessions          types.Int64  `tfsdk:"session_limits_max_sessions"`
	SessionLimitsConnectRateBurst     types.Int64  `tfsdk:"session_limits_connect_rate_burst"`
	SessionLimitsMaxWaitTime          types.Int64  `tfsdk:"session_limits_max_wait_time"`
	SessionPoolMaxSessions            types.Int64  `tfsdk:"session_pool_max_sessions"`
	SessionPoolIdleTime               types.Int64  `tfsdk:"session_pool_idle_time"`
	SessionPoolPoolMaxSessions        types.Int64  `tfsdk:"session_pool_pool_max_sessions"`
	CommitQueueEnabledByDefault       types.Bool   `tfsdk:"commit_queue_enabled_by_default"`
	CommitQueueAtomic                 types.Bool   `tfsdk:"commit_queue_atomic"`
	CommitQueueRetryAttempts          types.Int64  `tfsdk:"commit_queue_retry_attempts"`
	CommitQueueRetryTimeout           types.Int64  `tfsdk:"commit_queue_retry_timeout"`
	CommitQueueErrorOption            types.String `tfsdk:"commit_queue_error_option"`
	CommitRetriesAttempts             types.Int64  `tfsdk:"commit_retries_attempts"`
	CommitRetriesTimeout              types.Int64  `tfsdk:"commit_retries_timeout"`
	TraceDir                          types.String `tfsdk:"trace_dir"`
	ReportMultipleErrors              types.Bool   `tfsdk:"report_multiple_errors"`
}

type GlobalSettingsData struct {
	Instance                          types.String `tfsdk:"instance"`
	Id                                types.String `tfsdk:"id"`
	ConnectTimeout                    types.Int64  `tfsdk:"connect_timeout"`
	ReadTimeout                       types.Int64  `tfsdk:"read_timeout"`
	WriteTimeout                      types.Int64  `tfsdk:"write_timeout"`
	NoWaitForLock                     types.Bool   `tfsdk:"no_wait_for_lock"`
	WaitForLockTimeout                types.Int64  `tfsdk:"wait_for_lock_timeout"`
	WaitForLockInfinity               types.Bool   `tfsdk:"wait_for_lock_infinity"`
	SshKeepAliveInterval              types.Int64  `tfsdk:"ssh_keep_alive_interval"`
	SshKeepAliveCount                 types.Int64  `tfsdk:"ssh_keep_alive_count"`
	SshAlgorithmsPublicKey            types.List   `tfsdk:"ssh_algorithms_public_key"`
	SshAlgorithmsKex                  types.List   `tfsdk:"ssh_algorithms_kex"`
	SshAlgorithmsMac                  types.List   `tfsdk:"ssh_algorithms_mac"`
	SshAlgorithmsCipher               types.List   `tfsdk:"ssh_algorithms_cipher"`
	SshAlgorithmsCompression          types.List   `tfsdk:"ssh_algorithms_compression"`
	SshAlgorithmsDhGroupMinSize       types.Int64  `tfsdk:"ssh_algorithms_dh_group_min_size"`
	SshAlgorithmsDhGroupPreferredSize types.Int64  `tfsdk:"ssh_algorithms_dh_group_preferred_size"`
	SshAlgorithmsDhGroupMaxSize       types.Int64  `tfsdk:"ssh_algorithms_dh_group_max_size"`
	NedKeepAliveInterval              types.Int64  `tfsdk:"ned_keep_alive_interval"`
	NedKeepAliveCount                 types.Int64  `tfsdk:"ned_keep_alive_count"`
	ConnectRetriesAttempts            types.Int64  `tfsdk:"connect_retries_attempts"`
	ConnectRetriesTimeout             types.Int64  `tfsdk:"connect_retries_timeout"`
	Trace                             types.String `tfsdk:"trace"`
	TraceOutput                       types.String `tfsdk:"trace_output"`
	NedSettingsUseConfirmedCommit     types.Bool   `tfsdk:"ned_settings_use_confirmed_commit"`
	NedSettingsUseValidate            types.Bool   `tfsdk:"ned_settings_use_validate"`
	NedSettingsUseStartup             types.Bool   `tfsdk:"ned_settings_use_startup"`
	NedSettingsUseTransactionId       types.Bool   `tfsdk:"ned_settings_use_transaction_id"`
	NedSettingsUsePrivateCandidate    types.Bool   `tfsdk:"ned_settings_use_private_candidate"`
	NedSettingsUseJunosRollback       types.Bool   `tfsdk:"ned_settings_use_junos_rollback"`
	NoOverwriteEnabledByDefault       types.Bool   `tfsdk:"no_overwrite_enabled_by_default"`
	NoOverwriteCompare                types.String `tfsdk:"no_overwrite_compare"`
	LsaNoOverwriteEnabledByDefault    types.Bool   `tfsdk:"lsa_no_overwrite_enabled_by_default"`
	LsaNoOverwriteCompare             types.String `tfsdk:"lsa_no_overwrite_compare"`
	OutOfSyncCommitBehaviour          types.String `tfsdk:"out_of_sync_commit_behaviour"`
	UseLsa                            types.Bool   `tfsdk:"use_lsa"`
	NoLsa                             types.Bool   `tfsdk:"no_lsa"`
	SessionLimitsMaxSessions          types.Int64  `tfsdk:"session_limits_max_sessions"`
	SessionLimitsConnectRateBurst     types.Int64  `tfsdk:"session_limits_connect_rate_burst"`
	SessionLimitsMaxWaitTime          types.Int64  `tfsdk:"session_limits_max_wait_time"`
	SessionPoolMaxSessions            types.Int64  `tfsdk:"session_pool_max_sessions"`
	SessionPoolIdleTime               types.Int64  `tfsdk:"session_pool_idle_time"`
	SessionPoolPoolMaxSessions        types.Int64  `tfsdk:"session_pool_pool_max_sessions"`
	CommitQueueEnabledByDefault       types.Bool   `tfsdk:"commit_queue_enabled_by_default"`
	CommitQueueAtomic                 types.Bool   `tfsdk:"commit_queue_atomic"`
	CommitQueueRetryAttempts          types.Int64  `tfsdk:"commit_queue_retry_attempts"`
	CommitQueueRetryTimeout           types.Int64  `tfsdk:"commit_queue_retry_timeout"`
	CommitQueueErrorOption            types.String `tfsdk:"commit_queue_error_option"`
	CommitRetriesAttempts             types.Int64  `tfsdk:"commit_retries_attempts"`
	CommitRetriesTimeout              types.Int64  `tfsdk:"commit_retries_timeout"`
	TraceDir                          types.String `tfsdk:"trace_dir"`
	ReportMultipleErrors              types.Bool   `tfsdk:"report_multiple_errors"`
}

func (data GlobalSettings) getPath() string {
	return "tailf-ncs:devices/global-settings"
}

func (data GlobalSettingsData) getPath() string {
	return "tailf-ncs:devices/global-settings"
}

// if last path element has a key -> remove it
func (data GlobalSettings) getPathShort() string {
	path := data.getPath()
	re := regexp.MustCompile(`(.*)=[^\/]*$`)
	matches := re.FindStringSubmatch(path)
	if len(matches) <= 1 {
		return path
	}
	return matches[1]
}

func (data GlobalSettings) toBody(ctx context.Context) string {
	body := `{"` + helpers.LastElement(data.getPath()) + `":{}}`
	if !data.ConnectTimeout.IsNull() && !data.ConnectTimeout.IsUnknown() {
		body, _ = sjson.Set(body, helpers.LastElement(data.getPath())+"."+"connect-timeout", strconv.FormatInt(data.ConnectTimeout.ValueInt64(), 10))
	}
	if !data.ReadTimeout.IsNull() && !data.ReadTimeout.IsUnknown() {
		body, _ = sjson.Set(body, helpers.LastElement(data.getPath())+"."+"read-timeout", strconv.FormatInt(data.ReadTimeout.ValueInt64(), 10))
	}
	if !data.WriteTimeout.IsNull() && !data.WriteTimeout.IsUnknown() {
		body, _ = sjson.Set(body, helpers.LastElement(data.getPath())+"."+"write-timeout", strconv.FormatInt(data.WriteTimeout.ValueInt64(), 10))
	}
	if !data.NoWaitForLock.IsNull() && !data.NoWaitForLock.IsUnknown() {
		if data.NoWaitForLock.ValueBool() {
			body, _ = sjson.Set(body, helpers.LastElement(data.getPath())+"."+"no-wait-for-lock", map[string]string{})
		}
	}
	if !data.WaitForLockTimeout.IsNull() && !data.WaitForLockTimeout.IsUnknown() {
		body, _ = sjson.Set(body, helpers.LastElement(data.getPath())+"."+"wait-for-lock.timeout", strconv.FormatInt(data.WaitForLockTimeout.ValueInt64(), 10))
	}
	if !data.WaitForLockInfinity.IsNull() && !data.WaitForLockInfinity.IsUnknown() {
		if data.WaitForLockInfinity.ValueBool() {
			body, _ = sjson.Set(body, helpers.LastElement(data.getPath())+"."+"wait-for-lock.infinity", map[string]string{})
		}
	}
	if !data.SshKeepAliveInterval.IsNull() && !data.SshKeepAliveInterval.IsUnknown() {
		body, _ = sjson.Set(body, helpers.LastElement(data.getPath())+"."+"ssh.keep-alive-interval", strconv.FormatInt(data.SshKeepAliveInterval.ValueInt64(), 10))
	}
	if !data.SshKeepAliveCount.IsNull() && !data.SshKeepAliveCount.IsUnknown() {
		body, _ = sjson.Set(body, helpers.LastElement(data.getPath())+"."+"ssh.keep-alive-count", strconv.FormatInt(data.SshKeepAliveCount.ValueInt64(), 10))
	}
	if !data.SshAlgorithmsPublicKey.IsNull() && !data.SshAlgorithmsPublicKey.IsUnknown() {
		var values []string
		data.SshAlgorithmsPublicKey.ElementsAs(ctx, &values, false)
		body, _ = sjson.Set(body, helpers.LastElement(data.getPath())+"."+"ssh.algorithms.public-key", values)
	}
	if !data.SshAlgorithmsKex.IsNull() && !data.SshAlgorithmsKex.IsUnknown() {
		var values []string
		data.SshAlgorithmsKex.ElementsAs(ctx, &values, false)
		body, _ = sjson.Set(body, helpers.LastElement(data.getPath())+"."+"ssh.algorithms.kex", values)
	}
	if !data.SshAlgorithmsMac.IsNull() && !data.SshAlgorithmsMac.IsUnknown() {
		var values []string
		data.SshAlgorithmsMac.ElementsAs(ctx, &values, false)
		body, _ = sjson.Set(body, helpers.LastElement(data.getPath())+"."+"ssh.algorithms.mac", values)
	}
	if !data.SshAlgorithmsCipher.IsNull() && !data.SshAlgorithmsCipher.IsUnknown() {
		var values []string
		data.SshAlgorithmsCipher.ElementsAs(ctx, &values, false)
		body, _ = sjson.Set(body, helpers.LastElement(data.getPath())+"."+"ssh.algorithms.cipher", values)
	}
	if !data.SshAlgorithmsCompression.IsNull() && !data.SshAlgorithmsCompression.IsUnknown() {
		var values []string
		data.SshAlgorithmsCompression.ElementsAs(ctx, &values, false)
		body, _ = sjson.Set(body, helpers.LastElement(data.getPath())+"."+"ssh.algorithms.compression", values)
	}
	if !data.SshAlgorithmsDhGroupMinSize.IsNull() && !data.SshAlgorithmsDhGroupMinSize.IsUnknown() {
		body, _ = sjson.Set(body, helpers.LastElement(data.getPath())+"."+"ssh.algorithms.dh-group.min-size", strconv.FormatInt(data.SshAlgorithmsDhGroupMinSize.ValueInt64(), 10))
	}
	if !data.SshAlgorithmsDhGroupPreferredSize.IsNull() && !data.SshAlgorithmsDhGroupPreferredSize.IsUnknown() {
		body, _ = sjson.Set(body, helpers.LastElement(data.getPath())+"."+"ssh.algorithms.dh-group.preferred-size", strconv.FormatInt(data.SshAlgorithmsDhGroupPreferredSize.ValueInt64(), 10))
	}
	if !data.SshAlgorithmsDhGroupMaxSize.IsNull() && !data.SshAlgorithmsDhGroupMaxSize.IsUnknown() {
		body, _ = sjson.Set(body, helpers.LastElement(data.getPath())+"."+"ssh.algorithms.dh-group.max-size", strconv.FormatInt(data.SshAlgorithmsDhGroupMaxSize.ValueInt64(), 10))
	}
	if !data.NedKeepAliveInterval.IsNull() && !data.NedKeepAliveInterval.IsUnknown() {
		body, _ = sjson.Set(body, helpers.LastElement(data.getPath())+"."+"ned-keep-alive.interval", strconv.FormatInt(data.NedKeepAliveInterval.ValueInt64(), 10))
	}
	if !data.NedKeepAliveCount.IsNull() && !data.NedKeepAliveCount.IsUnknown() {
		body, _ = sjson.Set(body, helpers.LastElement(data.getPath())+"."+"ned-keep-alive.count", strconv.FormatInt(data.NedKeepAliveCount.ValueInt64(), 10))
	}
	if !data.ConnectRetriesAttempts.IsNull() && !data.ConnectRetriesAttempts.IsUnknown() {
		body, _ = sjson.Set(body, helpers.LastElement(data.getPath())+"."+"connect-retries.attempts", strconv.FormatInt(data.ConnectRetriesAttempts.ValueInt64(), 10))
	}
	if !data.ConnectRetriesTimeout.IsNull() && !data.ConnectRetriesTimeout.IsUnknown() {
		body, _ = sjson.Set(body, helpers.LastElement(data.getPath())+"."+"connect-retries.timeout", strconv.FormatInt(data.ConnectRetriesTimeout.ValueInt64(), 10))
	}
	if !data.Trace.IsNull() && !data.Trace.IsUnknown() {
		body, _ = sjson.Set(body, helpers.LastElement(data.getPath())+"."+"trace", data.Trace.ValueString())
	}
	if !data.TraceOutput.IsNull() && !data.TraceOutput.IsUnknown() {
		body, _ = sjson.Set(body, helpers.LastElement(data.getPath())+"."+"trace-output", data.TraceOutput.ValueString())
	}
	if !data.NedSettingsUseConfirmedCommit.IsNull() && !data.NedSettingsUseConfirmedCommit.IsUnknown() {
		if data.NedSettingsUseConfirmedCommit.ValueBool() {
			body, _ = sjson.Set(body, helpers.LastElement(data.getPath())+"."+"ned-settings.use-confirmed-commit", map[string]string{})
		}
	}
	if !data.NedSettingsUseValidate.IsNull() && !data.NedSettingsUseValidate.IsUnknown() {
		if data.NedSettingsUseValidate.ValueBool() {
			body, _ = sjson.Set(body, helpers.LastElement(data.getPath())+"."+"ned-settings.use-validate", map[string]string{})
		}
	}
	if !data.NedSettingsUseStartup.IsNull() && !data.NedSettingsUseStartup.IsUnknown() {
		if data.NedSettingsUseStartup.ValueBool() {
			body, _ = sjson.Set(body, helpers.LastElement(data.getPath())+"."+"ned-settings.use-startup", map[string]string{})
		}
	}
	if !data.NedSettingsUseTransactionId.IsNull() && !data.NedSettingsUseTransactionId.IsUnknown() {
		if data.NedSettingsUseTransactionId.ValueBool() {
			body, _ = sjson.Set(body, helpers.LastElement(data.getPath())+"."+"ned-settings.use-transaction-id", map[string]string{})
		}
	}
	if !data.NedSettingsUsePrivateCandidate.IsNull() && !data.NedSettingsUsePrivateCandidate.IsUnknown() {
		if data.NedSettingsUsePrivateCandidate.ValueBool() {
			body, _ = sjson.Set(body, helpers.LastElement(data.getPath())+"."+"ned-settings.use-private-candidate", map[string]string{})
		}
	}
	if !data.NedSettingsUseJunosRollback.IsNull() && !data.NedSettingsUseJunosRollback.IsUnknown() {
		if data.NedSettingsUseJunosRollback.ValueBool() {
			body, _ = sjson.Set(body, helpers.LastElement(data.getPath())+"."+"ned-settings.use-junos-rollback", map[string]string{})
		}
	}
	if !data.NoOverwriteEnabledByDefault.IsNull() && !data.NoOverwriteEnabledByDefault.IsUnknown() {
		if data.NoOverwriteEnabledByDefault.ValueBool() {
			body, _ = sjson.Set(body, helpers.LastElement(data.getPath())+"."+"no-overwrite.enabled-by-default", map[string]string{})
		}
	}
	if !data.NoOverwriteCompare.IsNull() && !data.NoOverwriteCompare.IsUnknown() {
		body, _ = sjson.Set(body, helpers.LastElement(data.getPath())+"."+"no-overwrite.compare", data.NoOverwriteCompare.ValueString())
	}
	if !data.LsaNoOverwriteEnabledByDefault.IsNull() && !data.LsaNoOverwriteEnabledByDefault.IsUnknown() {
		if data.LsaNoOverwriteEnabledByDefault.ValueBool() {
			body, _ = sjson.Set(body, helpers.LastElement(data.getPath())+"."+"lsa.no-overwrite.enabled-by-default", map[string]string{})
		}
	}
	if !data.LsaNoOverwriteCompare.IsNull() && !data.LsaNoOverwriteCompare.IsUnknown() {
		body, _ = sjson.Set(body, helpers.LastElement(data.getPath())+"."+"lsa.no-overwrite.compare", data.LsaNoOverwriteCompare.ValueString())
	}
	if !data.OutOfSyncCommitBehaviour.IsNull() && !data.OutOfSyncCommitBehaviour.IsUnknown() {
		body, _ = sjson.Set(body, helpers.LastElement(data.getPath())+"."+"out-of-sync-commit-behaviour", data.OutOfSyncCommitBehaviour.ValueString())
	}
	if !data.UseLsa.IsNull() && !data.UseLsa.IsUnknown() {
		if data.UseLsa.ValueBool() {
			body, _ = sjson.Set(body, helpers.LastElement(data.getPath())+"."+"use-lsa", map[string]string{})
		}
	}
	if !data.NoLsa.IsNull() && !data.NoLsa.IsUnknown() {
		if data.NoLsa.ValueBool() {
			body, _ = sjson.Set(body, helpers.LastElement(data.getPath())+"."+"no-lsa", map[string]string{})
		}
	}
	if !data.SessionLimitsMaxSessions.IsNull() && !data.SessionLimitsMaxSessions.IsUnknown() {
		body, _ = sjson.Set(body, helpers.LastElement(data.getPath())+"."+"session-limits.max-sessions", strconv.FormatInt(data.SessionLimitsMaxSessions.ValueInt64(), 10))
	}
	if !data.SessionLimitsConnectRateBurst.IsNull() && !data.SessionLimitsConnectRateBurst.IsUnknown() {
		body, _ = sjson.Set(body, helpers.LastElement(data.getPath())+"."+"session-limits.connect-rate.burst", strconv.FormatInt(data.SessionLimitsConnectRateBurst.ValueInt64(), 10))
	}
	if !data.SessionLimitsMaxWaitTime.IsNull() && !data.SessionLimitsMaxWaitTime.IsUnknown() {
		body, _ = sjson.Set(body, helpers.LastElement(data.getPath())+"."+"session-limits.max-wait-time", strconv.FormatInt(data.SessionLimitsMaxWaitTime.ValueInt64(), 10))
	}
	if !data.SessionPoolMaxSessions.IsNull() && !data.SessionPoolMaxSessions.IsUnknown() {
		body, _ = sjson.Set(body, helpers.LastElement(data.getPath())+"."+"session-pool.max-sessions", strconv.FormatInt(data.SessionPoolMaxSessions.ValueInt64(), 10))
	}
	if !data.SessionPoolIdleTime.IsNull() && !data.SessionPoolIdleTime.IsUnknown() {
		body, _ = sjson.Set(body, helpers.LastElement(data.getPath())+"."+"session-pool.idle-time", strconv.FormatInt(data.SessionPoolIdleTime.ValueInt64(), 10))
	}
	if !data.SessionPoolPoolMaxSessions.IsNull() && !data.SessionPoolPoolMaxSessions.IsUnknown() {
		body, _ = sjson.Set(body, helpers.LastElement(data.getPath())+"."+"session-pool.pool.max-sessions", strconv.FormatInt(data.SessionPoolPoolMaxSessions.ValueInt64(), 10))
	}
	if !data.CommitQueueEnabledByDefault.IsNull() && !data.CommitQueueEnabledByDefault.IsUnknown() {
		if data.CommitQueueEnabledByDefault.ValueBool() {
			body, _ = sjson.Set(body, helpers.LastElement(data.getPath())+"."+"commit-queue.enabled-by-default", map[string]string{})
		}
	}
	if !data.CommitQueueAtomic.IsNull() && !data.CommitQueueAtomic.IsUnknown() {
		body, _ = sjson.Set(body, helpers.LastElement(data.getPath())+"."+"commit-queue.atomic", data.CommitQueueAtomic.ValueBool())
	}
	if !data.CommitQueueRetryAttempts.IsNull() && !data.CommitQueueRetryAttempts.IsUnknown() {
		body, _ = sjson.Set(body, helpers.LastElement(data.getPath())+"."+"commit-queue.retry.attempts", strconv.FormatInt(data.CommitQueueRetryAttempts.ValueInt64(), 10))
	}
	if !data.CommitQueueRetryTimeout.IsNull() && !data.CommitQueueRetryTimeout.IsUnknown() {
		body, _ = sjson.Set(body, helpers.LastElement(data.getPath())+"."+"commit-queue.retry.timeout", strconv.FormatInt(data.CommitQueueRetryTimeout.ValueInt64(), 10))
	}
	if !data.CommitQueueErrorOption.IsNull() && !data.CommitQueueErrorOption.IsUnknown() {
		body, _ = sjson.Set(body, helpers.LastElement(data.getPath())+"."+"commit-queue.error-option", data.CommitQueueErrorOption.ValueString())
	}
	if !data.CommitRetriesAttempts.IsNull() && !data.CommitRetriesAttempts.IsUnknown() {
		body, _ = sjson.Set(body, helpers.LastElement(data.getPath())+"."+"commit-retries.attempts", strconv.FormatInt(data.CommitRetriesAttempts.ValueInt64(), 10))
	}
	if !data.CommitRetriesTimeout.IsNull() && !data.CommitRetriesTimeout.IsUnknown() {
		body, _ = sjson.Set(body, helpers.LastElement(data.getPath())+"."+"commit-retries.timeout", strconv.FormatInt(data.CommitRetriesTimeout.ValueInt64(), 10))
	}
	if !data.TraceDir.IsNull() && !data.TraceDir.IsUnknown() {
		body, _ = sjson.Set(body, helpers.LastElement(data.getPath())+"."+"trace-dir", data.TraceDir.ValueString())
	}
	if !data.ReportMultipleErrors.IsNull() && !data.ReportMultipleErrors.IsUnknown() {
		if data.ReportMultipleErrors.ValueBool() {
			body, _ = sjson.Set(body, helpers.LastElement(data.getPath())+"."+"report-multiple-errors", map[string]string{})
		}
	}
	return body
}

func (data *GlobalSettings) updateFromBody(ctx context.Context, res gjson.Result) {
	prefix := helpers.LastElement(data.getPath()) + "."
	if res.Get(helpers.LastElement(data.getPath())).IsArray() {
		prefix += "0."
	}
	if value := res.Get(prefix + "connect-timeout"); value.Exists() && !data.ConnectTimeout.IsNull() {
		data.ConnectTimeout = types.Int64Value(value.Int())
	} else {
		data.ConnectTimeout = types.Int64Null()
	}
	if value := res.Get(prefix + "read-timeout"); value.Exists() && !data.ReadTimeout.IsNull() {
		data.ReadTimeout = types.Int64Value(value.Int())
	} else {
		data.ReadTimeout = types.Int64Null()
	}
	if value := res.Get(prefix + "write-timeout"); value.Exists() && !data.WriteTimeout.IsNull() {
		data.WriteTimeout = types.Int64Value(value.Int())
	} else {
		data.WriteTimeout = types.Int64Null()
	}
	if value := res.Get(prefix + "no-wait-for-lock"); !data.NoWaitForLock.IsNull() {
		if value.Exists() {
			data.NoWaitForLock = types.BoolValue(true)
		} else {
			data.NoWaitForLock = types.BoolValue(false)
		}
	} else {
		data.NoWaitForLock = types.BoolNull()
	}
	if value := res.Get(prefix + "wait-for-lock.timeout"); value.Exists() && !data.WaitForLockTimeout.IsNull() {
		data.WaitForLockTimeout = types.Int64Value(value.Int())
	} else {
		data.WaitForLockTimeout = types.Int64Null()
	}
	if value := res.Get(prefix + "wait-for-lock.infinity"); !data.WaitForLockInfinity.IsNull() {
		if value.Exists() {
			data.WaitForLockInfinity = types.BoolValue(true)
		} else {
			data.WaitForLockInfinity = types.BoolValue(false)
		}
	} else {
		data.WaitForLockInfinity = types.BoolNull()
	}
	if value := res.Get(prefix + "ssh.keep-alive-interval"); value.Exists() && !data.SshKeepAliveInterval.IsNull() {
		data.SshKeepAliveInterval = types.Int64Value(value.Int())
	} else {
		data.SshKeepAliveInterval = types.Int64Null()
	}
	if value := res.Get(prefix + "ssh.keep-alive-count"); value.Exists() && !data.SshKeepAliveCount.IsNull() {
		data.SshKeepAliveCount = types.Int64Value(value.Int())
	} else {
		data.SshKeepAliveCount = types.Int64Null()
	}
	if value := res.Get(prefix + "ssh.algorithms.public-key"); value.Exists() && !data.SshAlgorithmsPublicKey.IsNull() {
		data.SshAlgorithmsPublicKey = helpers.GetStringList(value.Array())
	} else {
		data.SshAlgorithmsPublicKey = types.ListNull(types.StringType)
	}
	if value := res.Get(prefix + "ssh.algorithms.kex"); value.Exists() && !data.SshAlgorithmsKex.IsNull() {
		data.SshAlgorithmsKex = helpers.GetStringList(value.Array())
	} else {
		data.SshAlgorithmsKex = types.ListNull(types.StringType)
	}
	if value := res.Get(prefix + "ssh.algorithms.mac"); value.Exists() && !data.SshAlgorithmsMac.IsNull() {
		data.SshAlgorithmsMac = helpers.GetStringList(value.Array())
	} else {
		data.SshAlgorithmsMac = types.ListNull(types.StringType)
	}
	if value := res.Get(prefix + "ssh.algorithms.cipher"); value.Exists() && !data.SshAlgorithmsCipher.IsNull() {
		data.SshAlgorithmsCipher = helpers.GetStringList(value.Array())
	} else {
		data.SshAlgorithmsCipher = types.ListNull(types.StringType)
	}
	if value := res.Get(prefix + "ssh.algorithms.compression"); value.Exists() && !data.SshAlgorithmsCompression.IsNull() {
		data.SshAlgorithmsCompression = helpers.GetStringList(value.Array())
	} else {
		data.SshAlgorithmsCompression = types.ListNull(types.StringType)
	}
	if value := res.Get(prefix + "ssh.algorithms.dh-group.min-size"); value.Exists() && !data.SshAlgorithmsDhGroupMinSize.IsNull() {
		data.SshAlgorithmsDhGroupMinSize = types.Int64Value(value.Int())
	} else {
		data.SshAlgorithmsDhGroupMinSize = types.Int64Null()
	}
	if value := res.Get(prefix + "ssh.algorithms.dh-group.preferred-size"); value.Exists() && !data.SshAlgorithmsDhGroupPreferredSize.IsNull() {
		data.SshAlgorithmsDhGroupPreferredSize = types.Int64Value(value.Int())
	} else {
		data.SshAlgorithmsDhGroupPreferredSize = types.Int64Null()
	}
	if value := res.Get(prefix + "ssh.algorithms.dh-group.max-size"); value.Exists() && !data.SshAlgorithmsDhGroupMaxSize.IsNull() {
		data.SshAlgorithmsDhGroupMaxSize = types.Int64Value(value.Int())
	} else {
		data.SshAlgorithmsDhGroupMaxSize = types.Int64Null()
	}
	if value := res.Get(prefix + "ned-keep-alive.interval"); value.Exists() && !data.NedKeepAliveInterval.IsNull() {
		data.NedKeepAliveInterval = types.Int64Value(value.Int())
	} else {
		data.NedKeepAliveInterval = types.Int64Null()
	}
	if value := res.Get(prefix + "ned-keep-alive.count"); value.Exists() && !data.NedKeepAliveCount.IsNull() {
		data.NedKeepAliveCount = types.Int64Value(value.Int())
	} else {
		data.NedKeepAliveCount = types.Int64Null()
	}
	if value := res.Get(prefix + "connect-retries.attempts"); value.Exists() && !data.ConnectRetriesAttempts.IsNull() {
		data.ConnectRetriesAttempts = types.Int64Value(value.Int())
	} else {
		data.ConnectRetriesAttempts = types.Int64Null()
	}
	if value := res.Get(prefix + "connect-retries.timeout"); value.Exists() && !data.ConnectRetriesTimeout.IsNull() {
		data.ConnectRetriesTimeout = types.Int64Value(value.Int())
	} else {
		data.ConnectRetriesTimeout = types.Int64Null()
	}
	if value := res.Get(prefix + "trace"); value.Exists() && !data.Trace.IsNull() {
		data.Trace = types.StringValue(value.String())
	} else {
		data.Trace = types.StringNull()
	}
	if value := res.Get(prefix + "trace-output"); value.Exists() && !data.TraceOutput.IsNull() {
		data.TraceOutput = types.StringValue(value.String())
	} else {
		data.TraceOutput = types.StringNull()
	}
	if value := res.Get(prefix + "ned-settings.use-confirmed-commit"); !data.NedSettingsUseConfirmedCommit.IsNull() {
		if value.Exists() {
			data.NedSettingsUseConfirmedCommit = types.BoolValue(true)
		} else {
			data.NedSettingsUseConfirmedCommit = types.BoolValue(false)
		}
	} else {
		data.NedSettingsUseConfirmedCommit = types.BoolNull()
	}
	if value := res.Get(prefix + "ned-settings.use-validate"); !data.NedSettingsUseValidate.IsNull() {
		if value.Exists() {
			data.NedSettingsUseValidate = types.BoolValue(true)
		} else {
			data.NedSettingsUseValidate = types.BoolValue(false)
		}
	} else {
		data.NedSettingsUseValidate = types.BoolNull()
	}
	if value := res.Get(prefix + "ned-settings.use-startup"); !data.NedSettingsUseStartup.IsNull() {
		if value.Exists() {
			data.NedSettingsUseStartup = types.BoolValue(true)
		} else {
			data.NedSettingsUseStartup = types.BoolValue(false)
		}
	} else {
		data.NedSettingsUseStartup = types.BoolNull()
	}
	if value := res.Get(prefix + "ned-settings.use-transaction-id"); !data.NedSettingsUseTransactionId.IsNull() {
		if value.Exists() {
			data.NedSettingsUseTransactionId = types.BoolValue(true)
		} else {
			data.NedSettingsUseTransactionId = types.BoolValue(false)
		}
	} else {
		data.NedSettingsUseTransactionId = types.BoolNull()
	}
	if value := res.Get(prefix + "ned-settings.use-private-candidate"); !data.NedSettingsUsePrivateCandidate.IsNull() {
		if value.Exists() {
			data.NedSettingsUsePrivateCandidate = types.BoolValue(true)
		} else {
			data.NedSettingsUsePrivateCandidate = types.BoolValue(false)
		}
	} else {
		data.NedSettingsUsePrivateCandidate = types.BoolNull()
	}
	if value := res.Get(prefix + "ned-settings.use-junos-rollback"); !data.NedSettingsUseJunosRollback.IsNull() {
		if value.Exists() {
			data.NedSettingsUseJunosRollback = types.BoolValue(true)
		} else {
			data.NedSettingsUseJunosRollback = types.BoolValue(false)
		}
	} else {
		data.NedSettingsUseJunosRollback = types.BoolNull()
	}
	if value := res.Get(prefix + "no-overwrite.enabled-by-default"); !data.NoOverwriteEnabledByDefault.IsNull() {
		if value.Exists() {
			data.NoOverwriteEnabledByDefault = types.BoolValue(true)
		} else {
			data.NoOverwriteEnabledByDefault = types.BoolValue(false)
		}
	} else {
		data.NoOverwriteEnabledByDefault = types.BoolNull()
	}
	if value := res.Get(prefix + "no-overwrite.compare"); value.Exists() && !data.NoOverwriteCompare.IsNull() {
		data.NoOverwriteCompare = types.StringValue(value.String())
	} else {
		data.NoOverwriteCompare = types.StringNull()
	}
	if value := res.Get(prefix + "lsa.no-overwrite.enabled-by-default"); !data.LsaNoOverwriteEnabledByDefault.IsNull() {
		if value.Exists() {
			data.LsaNoOverwriteEnabledByDefault = types.BoolValue(true)
		} else {
			data.LsaNoOverwriteEnabledByDefault = types.BoolValue(false)
		}
	} else {
		data.LsaNoOverwriteEnabledByDefault = types.BoolNull()
	}
	if value := res.Get(prefix + "lsa.no-overwrite.compare"); value.Exists() && !data.LsaNoOverwriteCompare.IsNull() {
		data.LsaNoOverwriteCompare = types.StringValue(value.String())
	} else {
		data.LsaNoOverwriteCompare = types.StringNull()
	}
	if value := res.Get(prefix + "out-of-sync-commit-behaviour"); value.Exists() && !data.OutOfSyncCommitBehaviour.IsNull() {
		data.OutOfSyncCommitBehaviour = types.StringValue(value.String())
	} else {
		data.OutOfSyncCommitBehaviour = types.StringNull()
	}
	if value := res.Get(prefix + "use-lsa"); !data.UseLsa.IsNull() {
		if value.Exists() {
			data.UseLsa = types.BoolValue(true)
		} else {
			data.UseLsa = types.BoolValue(false)
		}
	} else {
		data.UseLsa = types.BoolNull()
	}
	if value := res.Get(prefix + "no-lsa"); !data.NoLsa.IsNull() {
		if value.Exists() {
			data.NoLsa = types.BoolValue(true)
		} else {
			data.NoLsa = types.BoolValue(false)
		}
	} else {
		data.NoLsa = types.BoolNull()
	}
	if value := res.Get(prefix + "session-limits.max-sessions"); value.Exists() && !data.SessionLimitsMaxSessions.IsNull() {
		data.SessionLimitsMaxSessions = types.Int64Value(value.Int())
	} else {
		data.SessionLimitsMaxSessions = types.Int64Null()
	}
	if value := res.Get(prefix + "session-limits.connect-rate.burst"); value.Exists() && !data.SessionLimitsConnectRateBurst.IsNull() {
		data.SessionLimitsConnectRateBurst = types.Int64Value(value.Int())
	} else {
		data.SessionLimitsConnectRateBurst = types.Int64Null()
	}
	if value := res.Get(prefix + "session-limits.max-wait-time"); value.Exists() && !data.SessionLimitsMaxWaitTime.IsNull() {
		data.SessionLimitsMaxWaitTime = types.Int64Value(value.Int())
	} else {
		data.SessionLimitsMaxWaitTime = types.Int64Null()
	}
	if value := res.Get(prefix + "session-pool.max-sessions"); value.Exists() && !data.SessionPoolMaxSessions.IsNull() {
		data.SessionPoolMaxSessions = types.Int64Value(value.Int())
	} else {
		data.SessionPoolMaxSessions = types.Int64Null()
	}
	if value := res.Get(prefix + "session-pool.idle-time"); value.Exists() && !data.SessionPoolIdleTime.IsNull() {
		data.SessionPoolIdleTime = types.Int64Value(value.Int())
	} else {
		data.SessionPoolIdleTime = types.Int64Null()
	}
	if value := res.Get(prefix + "session-pool.pool.max-sessions"); value.Exists() && !data.SessionPoolPoolMaxSessions.IsNull() {
		data.SessionPoolPoolMaxSessions = types.Int64Value(value.Int())
	} else {
		data.SessionPoolPoolMaxSessions = types.Int64Null()
	}
	if value := res.Get(prefix + "commit-queue.enabled-by-default"); !data.CommitQueueEnabledByDefault.IsNull() {
		if value.Exists() {
			data.CommitQueueEnabledByDefault = types.BoolValue(true)
		} else {
			data.CommitQueueEnabledByDefault = types.BoolValue(false)
		}
	} else {
		data.CommitQueueEnabledByDefault = types.BoolNull()
	}
	if value := res.Get(prefix + "commit-queue.atomic"); !data.CommitQueueAtomic.IsNull() {
		if value.Exists() {
			data.CommitQueueAtomic = types.BoolValue(value.Bool())
		}
	} else {
		data.CommitQueueAtomic = types.BoolNull()
	}
	if value := res.Get(prefix + "commit-queue.retry.attempts"); value.Exists() && !data.CommitQueueRetryAttempts.IsNull() {
		data.CommitQueueRetryAttempts = types.Int64Value(value.Int())
	} else {
		data.CommitQueueRetryAttempts = types.Int64Null()
	}
	if value := res.Get(prefix + "commit-queue.retry.timeout"); value.Exists() && !data.CommitQueueRetryTimeout.IsNull() {
		data.CommitQueueRetryTimeout = types.Int64Value(value.Int())
	} else {
		data.CommitQueueRetryTimeout = types.Int64Null()
	}
	if value := res.Get(prefix + "commit-queue.error-option"); value.Exists() && !data.CommitQueueErrorOption.IsNull() {
		data.CommitQueueErrorOption = types.StringValue(value.String())
	} else {
		data.CommitQueueErrorOption = types.StringNull()
	}
	if value := res.Get(prefix + "commit-retries.attempts"); value.Exists() && !data.CommitRetriesAttempts.IsNull() {
		data.CommitRetriesAttempts = types.Int64Value(value.Int())
	} else {
		data.CommitRetriesAttempts = types.Int64Null()
	}
	if value := res.Get(prefix + "commit-retries.timeout"); value.Exists() && !data.CommitRetriesTimeout.IsNull() {
		data.CommitRetriesTimeout = types.Int64Value(value.Int())
	} else {
		data.CommitRetriesTimeout = types.Int64Null()
	}
	if value := res.Get(prefix + "trace-dir"); value.Exists() && !data.TraceDir.IsNull() {
		data.TraceDir = types.StringValue(value.String())
	} else {
		data.TraceDir = types.StringNull()
	}
	if value := res.Get(prefix + "report-multiple-errors"); !data.ReportMultipleErrors.IsNull() {
		if value.Exists() {
			data.ReportMultipleErrors = types.BoolValue(true)
		} else {
			data.ReportMultipleErrors = types.BoolValue(false)
		}
	} else {
		data.ReportMultipleErrors = types.BoolNull()
	}
}

func (data *GlobalSettingsData) fromBody(ctx context.Context, res gjson.Result) {
	prefix := helpers.LastElement(data.getPath()) + "."
	if res.Get(helpers.LastElement(data.getPath())).IsArray() {
		prefix += "0."
	}
	if value := res.Get(prefix + "connect-timeout"); value.Exists() {
		data.ConnectTimeout = types.Int64Value(value.Int())
	}
	if value := res.Get(prefix + "read-timeout"); value.Exists() {
		data.ReadTimeout = types.Int64Value(value.Int())
	}
	if value := res.Get(prefix + "write-timeout"); value.Exists() {
		data.WriteTimeout = types.Int64Value(value.Int())
	}
	if value := res.Get(prefix + "no-wait-for-lock"); value.Exists() {
		data.NoWaitForLock = types.BoolValue(true)
	} else {
		data.NoWaitForLock = types.BoolValue(false)
	}
	if value := res.Get(prefix + "wait-for-lock.timeout"); value.Exists() {
		data.WaitForLockTimeout = types.Int64Value(value.Int())
	}
	if value := res.Get(prefix + "wait-for-lock.infinity"); value.Exists() {
		data.WaitForLockInfinity = types.BoolValue(true)
	} else {
		data.WaitForLockInfinity = types.BoolValue(false)
	}
	if value := res.Get(prefix + "ssh.keep-alive-interval"); value.Exists() {
		data.SshKeepAliveInterval = types.Int64Value(value.Int())
	}
	if value := res.Get(prefix + "ssh.keep-alive-count"); value.Exists() {
		data.SshKeepAliveCount = types.Int64Value(value.Int())
	}
	if value := res.Get(prefix + "ssh.algorithms.public-key"); value.Exists() {
		data.SshAlgorithmsPublicKey = helpers.GetStringList(value.Array())
	} else {
		data.SshAlgorithmsPublicKey = types.ListNull(types.StringType)
	}
	if value := res.Get(prefix + "ssh.algorithms.kex"); value.Exists() {
		data.SshAlgorithmsKex = helpers.GetStringList(value.Array())
	} else {
		data.SshAlgorithmsKex = types.ListNull(types.StringType)
	}
	if value := res.Get(prefix + "ssh.algorithms.mac"); value.Exists() {
		data.SshAlgorithmsMac = helpers.GetStringList(value.Array())
	} else {
		data.SshAlgorithmsMac = types.ListNull(types.StringType)
	}
	if value := res.Get(prefix + "ssh.algorithms.cipher"); value.Exists() {
		data.SshAlgorithmsCipher = helpers.GetStringList(value.Array())
	} else {
		data.SshAlgorithmsCipher = types.ListNull(types.StringType)
	}
	if value := res.Get(prefix + "ssh.algorithms.compression"); value.Exists() {
		data.SshAlgorithmsCompression = helpers.GetStringList(value.Array())
	} else {
		data.SshAlgorithmsCompression = types.ListNull(types.StringType)
	}
	if value := res.Get(prefix + "ssh.algorithms.dh-group.min-size"); value.Exists() {
		data.SshAlgorithmsDhGroupMinSize = types.Int64Value(value.Int())
	}
	if value := res.Get(prefix + "ssh.algorithms.dh-group.preferred-size"); value.Exists() {
		data.SshAlgorithmsDhGroupPreferredSize = types.Int64Value(value.Int())
	}
	if value := res.Get(prefix + "ssh.algorithms.dh-group.max-size"); value.Exists() {
		data.SshAlgorithmsDhGroupMaxSize = types.Int64Value(value.Int())
	}
	if value := res.Get(prefix + "ned-keep-alive.interval"); value.Exists() {
		data.NedKeepAliveInterval = types.Int64Value(value.Int())
	}
	if value := res.Get(prefix + "ned-keep-alive.count"); value.Exists() {
		data.NedKeepAliveCount = types.Int64Value(value.Int())
	}
	if value := res.Get(prefix + "connect-retries.attempts"); value.Exists() {
		data.ConnectRetriesAttempts = types.Int64Value(value.Int())
	}
	if value := res.Get(prefix + "connect-retries.timeout"); value.Exists() {
		data.ConnectRetriesTimeout = types.Int64Value(value.Int())
	}
	if value := res.Get(prefix + "trace"); value.Exists() {
		data.Trace = types.StringValue(value.String())
	}
	if value := res.Get(prefix + "trace-output"); value.Exists() {
		data.TraceOutput = types.StringValue(value.String())
	}
	if value := res.Get(prefix + "ned-settings.use-confirmed-commit"); value.Exists() {
		data.NedSettingsUseConfirmedCommit = types.BoolValue(true)
	} else {
		data.NedSettingsUseConfirmedCommit = types.BoolValue(false)
	}
	if value := res.Get(prefix + "ned-settings.use-validate"); value.Exists() {
		data.NedSettingsUseValidate = types.BoolValue(true)
	} else {
		data.NedSettingsUseValidate = types.BoolValue(false)
	}
	if value := res.Get(prefix + "ned-settings.use-startup"); value.Exists() {
		data.NedSettingsUseStartup = types.BoolValue(true)
	} else {
		data.NedSettingsUseStartup = types.BoolValue(false)
	}
	if value := res.Get(prefix + "ned-settings.use-transaction-id"); value.Exists() {
		data.NedSettingsUseTransactionId = types.BoolValue(true)
	} else {
		data.NedSettingsUseTransactionId = types.BoolValue(false)
	}
	if value := res.Get(prefix + "ned-settings.use-private-candidate"); value.Exists() {
		data.NedSettingsUsePrivateCandidate = types.BoolValue(true)
	} else {
		data.NedSettingsUsePrivateCandidate = types.BoolValue(false)
	}
	if value := res.Get(prefix + "ned-settings.use-junos-rollback"); value.Exists() {
		data.NedSettingsUseJunosRollback = types.BoolValue(true)
	} else {
		data.NedSettingsUseJunosRollback = types.BoolValue(false)
	}
	if value := res.Get(prefix + "no-overwrite.enabled-by-default"); value.Exists() {
		data.NoOverwriteEnabledByDefault = types.BoolValue(true)
	} else {
		data.NoOverwriteEnabledByDefault = types.BoolValue(false)
	}
	if value := res.Get(prefix + "no-overwrite.compare"); value.Exists() {
		data.NoOverwriteCompare = types.StringValue(value.String())
	}
	if value := res.Get(prefix + "lsa.no-overwrite.enabled-by-default"); value.Exists() {
		data.LsaNoOverwriteEnabledByDefault = types.BoolValue(true)
	} else {
		data.LsaNoOverwriteEnabledByDefault = types.BoolValue(false)
	}
	if value := res.Get(prefix + "lsa.no-overwrite.compare"); value.Exists() {
		data.LsaNoOverwriteCompare = types.StringValue(value.String())
	}
	if value := res.Get(prefix + "out-of-sync-commit-behaviour"); value.Exists() {
		data.OutOfSyncCommitBehaviour = types.StringValue(value.String())
	}
	if value := res.Get(prefix + "use-lsa"); value.Exists() {
		data.UseLsa = types.BoolValue(true)
	} else {
		data.UseLsa = types.BoolValue(false)
	}
	if value := res.Get(prefix + "no-lsa"); value.Exists() {
		data.NoLsa = types.BoolValue(true)
	} else {
		data.NoLsa = types.BoolValue(false)
	}
	if value := res.Get(prefix + "session-limits.max-sessions"); value.Exists() {
		data.SessionLimitsMaxSessions = types.Int64Value(value.Int())
	}
	if value := res.Get(prefix + "session-limits.connect-rate.burst"); value.Exists() {
		data.SessionLimitsConnectRateBurst = types.Int64Value(value.Int())
	}
	if value := res.Get(prefix + "session-limits.max-wait-time"); value.Exists() {
		data.SessionLimitsMaxWaitTime = types.Int64Value(value.Int())
	}
	if value := res.Get(prefix + "session-pool.max-sessions"); value.Exists() {
		data.SessionPoolMaxSessions = types.Int64Value(value.Int())
	}
	if value := res.Get(prefix + "session-pool.idle-time"); value.Exists() {
		data.SessionPoolIdleTime = types.Int64Value(value.Int())
	}
	if value := res.Get(prefix + "session-pool.pool.max-sessions"); value.Exists() {
		data.SessionPoolPoolMaxSessions = types.Int64Value(value.Int())
	}
	if value := res.Get(prefix + "commit-queue.enabled-by-default"); value.Exists() {
		data.CommitQueueEnabledByDefault = types.BoolValue(true)
	} else {
		data.CommitQueueEnabledByDefault = types.BoolValue(false)
	}
	if value := res.Get(prefix + "commit-queue.atomic"); value.Exists() {
		data.CommitQueueAtomic = types.BoolValue(value.Bool())
	} else {
		data.CommitQueueAtomic = types.BoolValue(false)
	}
	if value := res.Get(prefix + "commit-queue.retry.attempts"); value.Exists() {
		data.CommitQueueRetryAttempts = types.Int64Value(value.Int())
	}
	if value := res.Get(prefix + "commit-queue.retry.timeout"); value.Exists() {
		data.CommitQueueRetryTimeout = types.Int64Value(value.Int())
	}
	if value := res.Get(prefix + "commit-queue.error-option"); value.Exists() {
		data.CommitQueueErrorOption = types.StringValue(value.String())
	}
	if value := res.Get(prefix + "commit-retries.attempts"); value.Exists() {
		data.CommitRetriesAttempts = types.Int64Value(value.Int())
	}
	if value := res.Get(prefix + "commit-retries.timeout"); value.Exists() {
		data.CommitRetriesTimeout = types.Int64Value(value.Int())
	}
	if value := res.Get(prefix + "trace-dir"); value.Exists() {
		data.TraceDir = types.StringValue(value.String())
	}
	if value := res.Get(prefix + "report-multiple-errors"); value.Exists() {
		data.ReportMultipleErrors = types.BoolValue(true)
	} else {
		data.ReportMultipleErrors = types.BoolValue(false)
	}
}

func (data *GlobalSettings) getDeletedListItems(ctx context.Context, state GlobalSettings) []string {
	deletedListItems := make([]string, 0)
	return deletedListItems
}

func (data *GlobalSettings) getEmptyLeafsDelete(ctx context.Context) []string {
	emptyLeafsDelete := make([]string, 0)
	if !data.NoWaitForLock.IsNull() && !data.NoWaitForLock.ValueBool() {
		emptyLeafsDelete = append(emptyLeafsDelete, fmt.Sprintf("%v/no-wait-for-lock", data.getPath()))
	}
	if !data.WaitForLockInfinity.IsNull() && !data.WaitForLockInfinity.ValueBool() {
		emptyLeafsDelete = append(emptyLeafsDelete, fmt.Sprintf("%v/wait-for-lock/infinity", data.getPath()))
	}
	if !data.NedSettingsUseConfirmedCommit.IsNull() && !data.NedSettingsUseConfirmedCommit.ValueBool() {
		emptyLeafsDelete = append(emptyLeafsDelete, fmt.Sprintf("%v/ned-settings/use-confirmed-commit", data.getPath()))
	}
	if !data.NedSettingsUseValidate.IsNull() && !data.NedSettingsUseValidate.ValueBool() {
		emptyLeafsDelete = append(emptyLeafsDelete, fmt.Sprintf("%v/ned-settings/use-validate", data.getPath()))
	}
	if !data.NedSettingsUseStartup.IsNull() && !data.NedSettingsUseStartup.ValueBool() {
		emptyLeafsDelete = append(emptyLeafsDelete, fmt.Sprintf("%v/ned-settings/use-startup", data.getPath()))
	}
	if !data.NedSettingsUseTransactionId.IsNull() && !data.NedSettingsUseTransactionId.ValueBool() {
		emptyLeafsDelete = append(emptyLeafsDelete, fmt.Sprintf("%v/ned-settings/use-transaction-id", data.getPath()))
	}
	if !data.NedSettingsUsePrivateCandidate.IsNull() && !data.NedSettingsUsePrivateCandidate.ValueBool() {
		emptyLeafsDelete = append(emptyLeafsDelete, fmt.Sprintf("%v/ned-settings/use-private-candidate", data.getPath()))
	}
	if !data.NedSettingsUseJunosRollback.IsNull() && !data.NedSettingsUseJunosRollback.ValueBool() {
		emptyLeafsDelete = append(emptyLeafsDelete, fmt.Sprintf("%v/ned-settings/use-junos-rollback", data.getPath()))
	}
	if !data.NoOverwriteEnabledByDefault.IsNull() && !data.NoOverwriteEnabledByDefault.ValueBool() {
		emptyLeafsDelete = append(emptyLeafsDelete, fmt.Sprintf("%v/no-overwrite/enabled-by-default", data.getPath()))
	}
	if !data.LsaNoOverwriteEnabledByDefault.IsNull() && !data.LsaNoOverwriteEnabledByDefault.ValueBool() {
		emptyLeafsDelete = append(emptyLeafsDelete, fmt.Sprintf("%v/lsa/no-overwrite/enabled-by-default", data.getPath()))
	}
	if !data.UseLsa.IsNull() && !data.UseLsa.ValueBool() {
		emptyLeafsDelete = append(emptyLeafsDelete, fmt.Sprintf("%v/use-lsa", data.getPath()))
	}
	if !data.NoLsa.IsNull() && !data.NoLsa.ValueBool() {
		emptyLeafsDelete = append(emptyLeafsDelete, fmt.Sprintf("%v/no-lsa", data.getPath()))
	}
	if !data.CommitQueueEnabledByDefault.IsNull() && !data.CommitQueueEnabledByDefault.ValueBool() {
		emptyLeafsDelete = append(emptyLeafsDelete, fmt.Sprintf("%v/commit-queue/enabled-by-default", data.getPath()))
	}
	if !data.ReportMultipleErrors.IsNull() && !data.ReportMultipleErrors.ValueBool() {
		emptyLeafsDelete = append(emptyLeafsDelete, fmt.Sprintf("%v/report-multiple-errors", data.getPath()))
	}
	return emptyLeafsDelete
}

func (data *GlobalSettings) getDeletePaths(ctx context.Context) []string {
	var deletePaths []string
	if !data.ConnectTimeout.IsNull() {
		deletePaths = append(deletePaths, fmt.Sprintf("%v/connect-timeout", data.getPath()))
	}
	if !data.ReadTimeout.IsNull() {
		deletePaths = append(deletePaths, fmt.Sprintf("%v/read-timeout", data.getPath()))
	}
	if !data.WriteTimeout.IsNull() {
		deletePaths = append(deletePaths, fmt.Sprintf("%v/write-timeout", data.getPath()))
	}
	if !data.NoWaitForLock.IsNull() {
		deletePaths = append(deletePaths, fmt.Sprintf("%v/no-wait-for-lock", data.getPath()))
	}
	if !data.WaitForLockTimeout.IsNull() {
		deletePaths = append(deletePaths, fmt.Sprintf("%v/wait-for-lock/timeout", data.getPath()))
	}
	if !data.WaitForLockInfinity.IsNull() {
		deletePaths = append(deletePaths, fmt.Sprintf("%v/wait-for-lock/infinity", data.getPath()))
	}
	if !data.SshKeepAliveInterval.IsNull() {
		deletePaths = append(deletePaths, fmt.Sprintf("%v/ssh/keep-alive-interval", data.getPath()))
	}
	if !data.SshKeepAliveCount.IsNull() {
		deletePaths = append(deletePaths, fmt.Sprintf("%v/ssh/keep-alive-count", data.getPath()))
	}
	if !data.SshAlgorithmsPublicKey.IsNull() {
		deletePaths = append(deletePaths, fmt.Sprintf("%v/ssh/algorithms/public-key", data.getPath()))
	}
	if !data.SshAlgorithmsKex.IsNull() {
		deletePaths = append(deletePaths, fmt.Sprintf("%v/ssh/algorithms/kex", data.getPath()))
	}
	if !data.SshAlgorithmsMac.IsNull() {
		deletePaths = append(deletePaths, fmt.Sprintf("%v/ssh/algorithms/mac", data.getPath()))
	}
	if !data.SshAlgorithmsCipher.IsNull() {
		deletePaths = append(deletePaths, fmt.Sprintf("%v/ssh/algorithms/cipher", data.getPath()))
	}
	if !data.SshAlgorithmsCompression.IsNull() {
		deletePaths = append(deletePaths, fmt.Sprintf("%v/ssh/algorithms/compression", data.getPath()))
	}
	if !data.SshAlgorithmsDhGroupMinSize.IsNull() {
		deletePaths = append(deletePaths, fmt.Sprintf("%v/ssh/algorithms/dh-group/min-size", data.getPath()))
	}
	if !data.SshAlgorithmsDhGroupPreferredSize.IsNull() {
		deletePaths = append(deletePaths, fmt.Sprintf("%v/ssh/algorithms/dh-group/preferred-size", data.getPath()))
	}
	if !data.SshAlgorithmsDhGroupMaxSize.IsNull() {
		deletePaths = append(deletePaths, fmt.Sprintf("%v/ssh/algorithms/dh-group/max-size", data.getPath()))
	}
	if !data.NedKeepAliveInterval.IsNull() {
		deletePaths = append(deletePaths, fmt.Sprintf("%v/ned-keep-alive/interval", data.getPath()))
	}
	if !data.NedKeepAliveCount.IsNull() {
		deletePaths = append(deletePaths, fmt.Sprintf("%v/ned-keep-alive/count", data.getPath()))
	}
	if !data.ConnectRetriesAttempts.IsNull() {
		deletePaths = append(deletePaths, fmt.Sprintf("%v/connect-retries/attempts", data.getPath()))
	}
	if !data.ConnectRetriesTimeout.IsNull() {
		deletePaths = append(deletePaths, fmt.Sprintf("%v/connect-retries/timeout", data.getPath()))
	}
	if !data.Trace.IsNull() {
		deletePaths = append(deletePaths, fmt.Sprintf("%v/trace", data.getPath()))
	}
	if !data.TraceOutput.IsNull() {
		deletePaths = append(deletePaths, fmt.Sprintf("%v/trace-output", data.getPath()))
	}
	if !data.NedSettingsUseConfirmedCommit.IsNull() {
		deletePaths = append(deletePaths, fmt.Sprintf("%v/ned-settings/use-confirmed-commit", data.getPath()))
	}
	if !data.NedSettingsUseValidate.IsNull() {
		deletePaths = append(deletePaths, fmt.Sprintf("%v/ned-settings/use-validate", data.getPath()))
	}
	if !data.NedSettingsUseStartup.IsNull() {
		deletePaths = append(deletePaths, fmt.Sprintf("%v/ned-settings/use-startup", data.getPath()))
	}
	if !data.NedSettingsUseTransactionId.IsNull() {
		deletePaths = append(deletePaths, fmt.Sprintf("%v/ned-settings/use-transaction-id", data.getPath()))
	}
	if !data.NedSettingsUsePrivateCandidate.IsNull() {
		deletePaths = append(deletePaths, fmt.Sprintf("%v/ned-settings/use-private-candidate", data.getPath()))
	}
	if !data.NedSettingsUseJunosRollback.IsNull() {
		deletePaths = append(deletePaths, fmt.Sprintf("%v/ned-settings/use-junos-rollback", data.getPath()))
	}
	if !data.NoOverwriteEnabledByDefault.IsNull() {
		deletePaths = append(deletePaths, fmt.Sprintf("%v/no-overwrite/enabled-by-default", data.getPath()))
	}
	if !data.NoOverwriteCompare.IsNull() {
		deletePaths = append(deletePaths, fmt.Sprintf("%v/no-overwrite/compare", data.getPath()))
	}
	if !data.LsaNoOverwriteEnabledByDefault.IsNull() {
		deletePaths = append(deletePaths, fmt.Sprintf("%v/lsa/no-overwrite/enabled-by-default", data.getPath()))
	}
	if !data.LsaNoOverwriteCompare.IsNull() {
		deletePaths = append(deletePaths, fmt.Sprintf("%v/lsa/no-overwrite/compare", data.getPath()))
	}
	if !data.OutOfSyncCommitBehaviour.IsNull() {
		deletePaths = append(deletePaths, fmt.Sprintf("%v/out-of-sync-commit-behaviour", data.getPath()))
	}
	if !data.UseLsa.IsNull() {
		deletePaths = append(deletePaths, fmt.Sprintf("%v/use-lsa", data.getPath()))
	}
	if !data.NoLsa.IsNull() {
		deletePaths = append(deletePaths, fmt.Sprintf("%v/no-lsa", data.getPath()))
	}
	if !data.SessionLimitsMaxSessions.IsNull() {
		deletePaths = append(deletePaths, fmt.Sprintf("%v/session-limits/max-sessions", data.getPath()))
	}
	if !data.SessionLimitsConnectRateBurst.IsNull() {
		deletePaths = append(deletePaths, fmt.Sprintf("%v/session-limits/connect-rate/burst", data.getPath()))
	}
	if !data.SessionLimitsMaxWaitTime.IsNull() {
		deletePaths = append(deletePaths, fmt.Sprintf("%v/session-limits/max-wait-time", data.getPath()))
	}
	if !data.SessionPoolMaxSessions.IsNull() {
		deletePaths = append(deletePaths, fmt.Sprintf("%v/session-pool/max-sessions", data.getPath()))
	}
	if !data.SessionPoolIdleTime.IsNull() {
		deletePaths = append(deletePaths, fmt.Sprintf("%v/session-pool/idle-time", data.getPath()))
	}
	if !data.SessionPoolPoolMaxSessions.IsNull() {
		deletePaths = append(deletePaths, fmt.Sprintf("%v/session-pool/pool/max-sessions", data.getPath()))
	}
	if !data.CommitQueueEnabledByDefault.IsNull() {
		deletePaths = append(deletePaths, fmt.Sprintf("%v/commit-queue/enabled-by-default", data.getPath()))
	}
	if !data.CommitQueueAtomic.IsNull() {
		deletePaths = append(deletePaths, fmt.Sprintf("%v/commit-queue/atomic", data.getPath()))
	}
	if !data.CommitQueueRetryAttempts.IsNull() {
		deletePaths = append(deletePaths, fmt.Sprintf("%v/commit-queue/retry/attempts", data.getPath()))
	}
	if !data.CommitQueueRetryTimeout.IsNull() {
		deletePaths = append(deletePaths, fmt.Sprintf("%v/commit-queue/retry/timeout", data.getPath()))
	}
	if !data.CommitQueueErrorOption.IsNull() {
		deletePaths = append(deletePaths, fmt.Sprintf("%v/commit-queue/error-option", data.getPath()))
	}
	if !data.CommitRetriesAttempts.IsNull() {
		deletePaths = append(deletePaths, fmt.Sprintf("%v/commit-retries/attempts", data.getPath()))
	}
	if !data.CommitRetriesTimeout.IsNull() {
		deletePaths = append(deletePaths, fmt.Sprintf("%v/commit-retries/timeout", data.getPath()))
	}
	if !data.TraceDir.IsNull() {
		deletePaths = append(deletePaths, fmt.Sprintf("%v/trace-dir", data.getPath()))
	}
	if !data.ReportMultipleErrors.IsNull() {
		deletePaths = append(deletePaths, fmt.Sprintf("%v/report-multiple-errors", data.getPath()))
	}
	return deletePaths
}
