// Copyright © 2023 Cisco Systems, Inc. and its affiliates.
// All rights reserved.
//
// Licensed under the Mozilla Public License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://mozilla.org/MPL/2.0/
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// SPDX-License-Identifier: MPL-2.0

// Code generated by "gen/generator.go"; DO NOT EDIT.

package provider

import (
	"testing"

	"github.com/hashicorp/terraform-plugin-testing/helper/resource"
)

func TestAccNsoGlobalSettings(t *testing.T) {
	resource.Test(t, resource.TestCase{
		PreCheck:                 func() { testAccPreCheck(t) },
		ProtoV6ProviderFactories: testAccProtoV6ProviderFactories,
		Steps: []resource.TestStep{
			{
				Config: testAccNsoGlobalSettingsConfig_all(),
				Check: resource.ComposeTestCheckFunc(
					resource.TestCheckResourceAttr("nso_global_settings.test", "connect_timeout", "60"),
					resource.TestCheckResourceAttr("nso_global_settings.test", "read_timeout", "120"),
					resource.TestCheckResourceAttr("nso_global_settings.test", "write_timeout", "120"),
					resource.TestCheckResourceAttr("nso_global_settings.test", "no_wait_for_lock", "false"),
					resource.TestCheckResourceAttr("nso_global_settings.test", "wait_for_lock_timeout", "60"),
					resource.TestCheckResourceAttr("nso_global_settings.test", "wait_for_lock_infinity", "false"),
					resource.TestCheckResourceAttr("nso_global_settings.test", "ssh_keep_alive_interval", "20"),
					resource.TestCheckResourceAttr("nso_global_settings.test", "ssh_keep_alive_count", "3"),
					resource.TestCheckResourceAttr("nso_global_settings.test", "ssh_algorithms_public_key.0", "ssh-rsa"),
					resource.TestCheckResourceAttr("nso_global_settings.test", "ssh_algorithms_kex.0", "diffie-hellman-group14-sha1"),
					resource.TestCheckResourceAttr("nso_global_settings.test", "ssh_algorithms_mac.0", "hmac-sha2-256"),
					resource.TestCheckResourceAttr("nso_global_settings.test", "ssh_algorithms_cipher.0", "aes256-ctr"),
					resource.TestCheckResourceAttr("nso_global_settings.test", "ssh_algorithms_compression.0", "none"),
					resource.TestCheckResourceAttr("nso_global_settings.test", "ssh_algorithms_dh_group_min_size", "1024"),
					resource.TestCheckResourceAttr("nso_global_settings.test", "ssh_algorithms_dh_group_preferred_size", "2048"),
					resource.TestCheckResourceAttr("nso_global_settings.test", "ssh_algorithms_dh_group_max_size", "4096"),
					resource.TestCheckResourceAttr("nso_global_settings.test", "ned_keep_alive_interval", "120"),
					resource.TestCheckResourceAttr("nso_global_settings.test", "ned_keep_alive_count", "3"),
					resource.TestCheckResourceAttr("nso_global_settings.test", "connect_retries_attempts", "0"),
					resource.TestCheckResourceAttr("nso_global_settings.test", "connect_retries_timeout", "3"),
					resource.TestCheckResourceAttr("nso_global_settings.test", "trace", "false"),
					resource.TestCheckResourceAttr("nso_global_settings.test", "trace_output", "file"),
					resource.TestCheckResourceAttr("nso_global_settings.test", "ned_settings_use_confirmed_commit", "false"),
					resource.TestCheckResourceAttr("nso_global_settings.test", "ned_settings_use_validate", "false"),
					resource.TestCheckResourceAttr("nso_global_settings.test", "ned_settings_use_startup", "false"),
					resource.TestCheckResourceAttr("nso_global_settings.test", "ned_settings_use_transaction_id", "false"),
					resource.TestCheckResourceAttr("nso_global_settings.test", "ned_settings_use_private_candidate", "false"),
					resource.TestCheckResourceAttr("nso_global_settings.test", "ned_settings_use_junos_rollback", "false"),
					resource.TestCheckResourceAttr("nso_global_settings.test", "no_overwrite_enabled_by_default", "false"),
					resource.TestCheckResourceAttr("nso_global_settings.test", "no_overwrite_compare", "full"),
					resource.TestCheckResourceAttr("nso_global_settings.test", "lsa_no_overwrite_enabled_by_default", "false"),
					resource.TestCheckResourceAttr("nso_global_settings.test", "lsa_no_overwrite_compare", "full"),
					resource.TestCheckResourceAttr("nso_global_settings.test", "out_of_sync_commit_behaviour", "reject"),
					resource.TestCheckResourceAttr("nso_global_settings.test", "use_lsa", "false"),
					resource.TestCheckResourceAttr("nso_global_settings.test", "no_lsa", "false"),
					resource.TestCheckResourceAttr("nso_global_settings.test", "session_limits_max_sessions", "0"),
					resource.TestCheckResourceAttr("nso_global_settings.test", "session_limits_connect_rate_burst", "0"),
					resource.TestCheckResourceAttr("nso_global_settings.test", "session_limits_max_wait_time", "0"),
					resource.TestCheckResourceAttr("nso_global_settings.test", "session_pool_max_sessions", "0"),
					resource.TestCheckResourceAttr("nso_global_settings.test", "session_pool_idle_time", "0"),
					resource.TestCheckResourceAttr("nso_global_settings.test", "session_pool_pool_max_sessions", "0"),
					resource.TestCheckResourceAttr("nso_global_settings.test", "commit_queue_enabled_by_default", "false"),
					resource.TestCheckResourceAttr("nso_global_settings.test", "commit_queue_atomic", "true"),
					resource.TestCheckResourceAttr("nso_global_settings.test", "commit_queue_retry_attempts", "0"),
					resource.TestCheckResourceAttr("nso_global_settings.test", "commit_queue_retry_timeout", "30"),
					resource.TestCheckResourceAttr("nso_global_settings.test", "commit_queue_error_option", "continue-on-error"),
					resource.TestCheckResourceAttr("nso_global_settings.test", "commit_retries_attempts", "0"),
					resource.TestCheckResourceAttr("nso_global_settings.test", "commit_retries_timeout", "3"),
					resource.TestCheckResourceAttr("nso_global_settings.test", "trace_dir", "./logs"),
					resource.TestCheckResourceAttr("nso_global_settings.test", "report_multiple_errors", "false"),
				),
			},
			{
				ResourceName:  "nso_global_settings.test",
				ImportState:   true,
				ImportStateId: "tailf-ncs:devices/global-settings",
			},
		},
	})
}

func testAccNsoGlobalSettingsConfig_minimum() string {
	return `
	resource "nso_global_settings" "test" {
	}
	`
}

func testAccNsoGlobalSettingsConfig_all() string {
	return `
	resource "nso_global_settings" "test" {
		connect_timeout = 60
		read_timeout = 120
		write_timeout = 120
		no_wait_for_lock = false
		wait_for_lock_timeout = 60
		wait_for_lock_infinity = false
		ssh_keep_alive_interval = 20
		ssh_keep_alive_count = 3
		ssh_algorithms_public_key = ["ssh-rsa"]
		ssh_algorithms_kex = ["diffie-hellman-group14-sha1"]
		ssh_algorithms_mac = ["hmac-sha2-256"]
		ssh_algorithms_cipher = ["aes256-ctr"]
		ssh_algorithms_compression = ["none"]
		ssh_algorithms_dh_group_min_size = 1024
		ssh_algorithms_dh_group_preferred_size = 2048
		ssh_algorithms_dh_group_max_size = 4096
		ned_keep_alive_interval = 120
		ned_keep_alive_count = 3
		connect_retries_attempts = 0
		connect_retries_timeout = 3
		trace = "false"
		trace_output = "file"
		ned_settings_use_confirmed_commit = false
		ned_settings_use_validate = false
		ned_settings_use_startup = false
		ned_settings_use_transaction_id = false
		ned_settings_use_private_candidate = false
		ned_settings_use_junos_rollback = false
		no_overwrite_enabled_by_default = false
		no_overwrite_compare = "full"
		lsa_no_overwrite_enabled_by_default = false
		lsa_no_overwrite_compare = "full"
		out_of_sync_commit_behaviour = "reject"
		use_lsa = false
		no_lsa = false
		session_limits_max_sessions = 0
		session_limits_connect_rate_burst = 0
		session_limits_max_wait_time = 0
		session_pool_max_sessions = 0
		session_pool_idle_time = 0
		session_pool_pool_max_sessions = 0
		commit_queue_enabled_by_default = false
		commit_queue_atomic = true
		commit_queue_retry_attempts = 0
		commit_queue_retry_timeout = 30
		commit_queue_error_option = "continue-on-error"
		commit_retries_attempts = 0
		commit_retries_timeout = 3
		trace_dir = "./logs"
		report_multiple_errors = false
	}
	`
}
