// Copyright © 2023 Cisco Systems, Inc. and its affiliates.
// All rights reserved.
//
// Licensed under the Mozilla Public License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://mozilla.org/MPL/2.0/
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// SPDX-License-Identifier: MPL-2.0

// Code generated by "gen/generator.go"; DO NOT EDIT.

package provider

import (
	"context"
	"fmt"

	"github.com/CiscoDevNet/terraform-provider-nso/internal/provider/helpers"
	"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator"
	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-log/tflog"
	"github.com/netascode/go-restconf"
)

func NewGlobalSettingsResource() resource.Resource {
	return &GlobalSettingsResource{}
}

type GlobalSettingsResource struct {
	clients map[string]*restconf.Client
}

func (r *GlobalSettingsResource) Metadata(_ context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_global_settings"
}

func (r *GlobalSettingsResource) Schema(ctx context.Context, req resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		// This description is used by the documentation generator and the language server.
		MarkdownDescription: "This resource can manage the Global Settings configuration.",

		Attributes: map[string]schema.Attribute{
			"instance": schema.StringAttribute{
				MarkdownDescription: "An instance name from the provider configuration.",
				Optional:            true,
			},
			"id": schema.StringAttribute{
				MarkdownDescription: "The RESTCONF path.",
				Computed:            true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"connect_timeout": schema.Int64Attribute{
				MarkdownDescription: helpers.NewAttributeDescription("Timeout in seconds for new connections.").String,
				Optional:            true,
			},
			"read_timeout": schema.Int64Attribute{
				MarkdownDescription: helpers.NewAttributeDescription("Timeout in seconds used when reading data.").String,
				Optional:            true,
			},
			"write_timeout": schema.Int64Attribute{
				MarkdownDescription: helpers.NewAttributeDescription("Timeout in seconds used when writing data.").String,
				Optional:            true,
			},
			"no_wait_for_lock": schema.BoolAttribute{
				MarkdownDescription: helpers.NewAttributeDescription("Do not wait for the device lock, fail immediately.").String,
				Optional:            true,
			},
			"wait_for_lock_timeout": schema.Int64Attribute{
				MarkdownDescription: helpers.NewAttributeDescription("Timeout in seconds to wait for device lock.").String,
				Optional:            true,
			},
			"wait_for_lock_infinity": schema.BoolAttribute{
				MarkdownDescription: helpers.NewAttributeDescription("Wait indefinitely for the device lock.").String,
				Optional:            true,
			},
			"ssh_keep_alive_interval": schema.Int64Attribute{
				MarkdownDescription: helpers.NewAttributeDescription("The SSH keep alive interval in seconds.").String,
				Optional:            true,
			},
			"ssh_keep_alive_count": schema.Int64Attribute{
				MarkdownDescription: helpers.NewAttributeDescription("The number of SSH keep alive messages before disconnect.").String,
				Optional:            true,
			},
			"ssh_algorithms_public_key": schema.ListAttribute{
				MarkdownDescription: helpers.NewAttributeDescription("A list of SSH public key algorithms.").String,
				ElementType:         types.StringType,
				Optional:            true,
			},
			"ssh_algorithms_kex": schema.ListAttribute{
				MarkdownDescription: helpers.NewAttributeDescription("A list of SSH key exchange algorithms.").String,
				ElementType:         types.StringType,
				Optional:            true,
			},
			"ssh_algorithms_mac": schema.ListAttribute{
				MarkdownDescription: helpers.NewAttributeDescription("A list of SSH MAC algorithms.").String,
				ElementType:         types.StringType,
				Optional:            true,
			},
			"ssh_algorithms_cipher": schema.ListAttribute{
				MarkdownDescription: helpers.NewAttributeDescription("A list of SSH cipher algorithms.").String,
				ElementType:         types.StringType,
				Optional:            true,
			},
			"ssh_algorithms_compression": schema.ListAttribute{
				MarkdownDescription: helpers.NewAttributeDescription("A list of SSH compression algorithms.").String,
				ElementType:         types.StringType,
				Optional:            true,
			},
			"ssh_algorithms_dh_group_min_size": schema.Int64Attribute{
				MarkdownDescription: helpers.NewAttributeDescription("Minimum size of the DH group.").String,
				Optional:            true,
			},
			"ssh_algorithms_dh_group_preferred_size": schema.Int64Attribute{
				MarkdownDescription: helpers.NewAttributeDescription("Preferred size of the DH group.").String,
				Optional:            true,
			},
			"ssh_algorithms_dh_group_max_size": schema.Int64Attribute{
				MarkdownDescription: helpers.NewAttributeDescription("Maximum size of the DH group.").String,
				Optional:            true,
			},
			"ned_keep_alive_interval": schema.Int64Attribute{
				MarkdownDescription: helpers.NewAttributeDescription("The NED keep alive interval in seconds.").String,
				Optional:            true,
			},
			"ned_keep_alive_count": schema.Int64Attribute{
				MarkdownDescription: helpers.NewAttributeDescription("The number of NED keep alive messages before disconnect.").String,
				Optional:            true,
			},
			"connect_retries_attempts": schema.Int64Attribute{
				MarkdownDescription: helpers.NewAttributeDescription("Number of connection retry attempts.").String,
				Optional:            true,
			},
			"connect_retries_timeout": schema.Int64Attribute{
				MarkdownDescription: helpers.NewAttributeDescription("Timeout in seconds between connection retry attempts.").String,
				Optional:            true,
			},
			"trace": schema.StringAttribute{
				MarkdownDescription: helpers.NewAttributeDescription("Trace output control.").AddStringEnumDescription("raw", "pretty", "false").String,
				Optional:            true,
				Validators: []validator.String{
					stringvalidator.OneOf("raw", "pretty", "false"),
				},
			},
			"trace_output": schema.StringAttribute{
				MarkdownDescription: helpers.NewAttributeDescription("Where to send trace output.").AddStringEnumDescription("file", "stream").String,
				Optional:            true,
				Validators: []validator.String{
					stringvalidator.OneOf("file", "stream"),
				},
			},
			"ned_settings_use_confirmed_commit": schema.BoolAttribute{
				MarkdownDescription: helpers.NewAttributeDescription("Use confirmed commit toward the device.").String,
				Optional:            true,
			},
			"ned_settings_use_validate": schema.BoolAttribute{
				MarkdownDescription: helpers.NewAttributeDescription("Use validate toward the device.").String,
				Optional:            true,
			},
			"ned_settings_use_startup": schema.BoolAttribute{
				MarkdownDescription: helpers.NewAttributeDescription("Use startup datastore toward the device.").String,
				Optional:            true,
			},
			"ned_settings_use_transaction_id": schema.BoolAttribute{
				MarkdownDescription: helpers.NewAttributeDescription("Use transaction ID toward the device.").String,
				Optional:            true,
			},
			"ned_settings_use_private_candidate": schema.BoolAttribute{
				MarkdownDescription: helpers.NewAttributeDescription("Use private candidate datastore toward the device.").String,
				Optional:            true,
			},
			"ned_settings_use_junos_rollback": schema.BoolAttribute{
				MarkdownDescription: helpers.NewAttributeDescription("Use Junos rollback mechanism.").String,
				Optional:            true,
			},
			"no_overwrite_enabled_by_default": schema.BoolAttribute{
				MarkdownDescription: helpers.NewAttributeDescription("Enable no-overwrite by default.").String,
				Optional:            true,
			},
			"no_overwrite_compare": schema.StringAttribute{
				MarkdownDescription: helpers.NewAttributeDescription("No-overwrite comparison method.").AddStringEnumDescription("full", "revision").String,
				Optional:            true,
				Validators: []validator.String{
					stringvalidator.OneOf("full", "revision"),
				},
			},
			"lsa_no_overwrite_enabled_by_default": schema.BoolAttribute{
				MarkdownDescription: helpers.NewAttributeDescription("Enable LSA no-overwrite by default.").String,
				Optional:            true,
			},
			"lsa_no_overwrite_compare": schema.StringAttribute{
				MarkdownDescription: helpers.NewAttributeDescription("LSA no-overwrite comparison method.").AddStringEnumDescription("full", "revision").String,
				Optional:            true,
				Validators: []validator.String{
					stringvalidator.OneOf("full", "revision"),
				},
			},
			"out_of_sync_commit_behaviour": schema.StringAttribute{
				MarkdownDescription: helpers.NewAttributeDescription("How to handle out-of-sync devices during commit.").AddStringEnumDescription("reject", "accept").String,
				Optional:            true,
				Validators: []validator.String{
					stringvalidator.OneOf("reject", "accept"),
				},
			},
			"use_lsa": schema.BoolAttribute{
				MarkdownDescription: helpers.NewAttributeDescription("Use LSA (Layered Service Architecture).").String,
				Optional:            true,
			},
			"no_lsa": schema.BoolAttribute{
				MarkdownDescription: helpers.NewAttributeDescription("Disable LSA.").String,
				Optional:            true,
			},
			"session_limits_max_sessions": schema.Int64Attribute{
				MarkdownDescription: helpers.NewAttributeDescription("Maximum number of concurrent sessions.").String,
				Optional:            true,
			},
			"session_limits_connect_rate_burst": schema.Int64Attribute{
				MarkdownDescription: helpers.NewAttributeDescription("Maximum burst of connections allowed.").String,
				Optional:            true,
			},
			"session_limits_max_wait_time": schema.Int64Attribute{
				MarkdownDescription: helpers.NewAttributeDescription("Maximum time in seconds to wait for a session.").String,
				Optional:            true,
			},
			"session_pool_max_sessions": schema.Int64Attribute{
				MarkdownDescription: helpers.NewAttributeDescription("Maximum number of pooled sessions.").String,
				Optional:            true,
			},
			"session_pool_idle_time": schema.Int64Attribute{
				MarkdownDescription: helpers.NewAttributeDescription("Idle time in seconds before a pooled session is closed.").String,
				Optional:            true,
			},
			"session_pool_pool_max_sessions": schema.Int64Attribute{
				MarkdownDescription: helpers.NewAttributeDescription("Maximum number of sessions in the connection pool.").String,
				Optional:            true,
			},
			"commit_queue_enabled_by_default": schema.BoolAttribute{
				MarkdownDescription: helpers.NewAttributeDescription("Enable commit queue by default.").String,
				Optional:            true,
			},
			"commit_queue_atomic": schema.BoolAttribute{
				MarkdownDescription: helpers.NewAttributeDescription("Whether commit queue operations are atomic.").String,
				Optional:            true,
			},
			"commit_queue_retry_attempts": schema.Int64Attribute{
				MarkdownDescription: helpers.NewAttributeDescription("Number of commit queue retry attempts.").String,
				Optional:            true,
			},
			"commit_queue_retry_timeout": schema.Int64Attribute{
				MarkdownDescription: helpers.NewAttributeDescription("Timeout in seconds between commit queue retry attempts.").String,
				Optional:            true,
			},
			"commit_queue_error_option": schema.StringAttribute{
				MarkdownDescription: helpers.NewAttributeDescription("Commit queue error handling option.").AddStringEnumDescription("continue-on-error", "rollback-on-error", "stop-on-error").String,
				Optional:            true,
				Validators: []validator.String{
					stringvalidator.OneOf("continue-on-error", "rollback-on-error", "stop-on-error"),
				},
			},
			"commit_retries_attempts": schema.Int64Attribute{
				MarkdownDescription: helpers.NewAttributeDescription("Number of commit retry attempts.").String,
				Optional:            true,
			},
			"commit_retries_timeout": schema.Int64Attribute{
				MarkdownDescription: helpers.NewAttributeDescription("Timeout in seconds between commit retry attempts.").String,
				Optional:            true,
			},
			"trace_dir": schema.StringAttribute{
				MarkdownDescription: helpers.NewAttributeDescription("The directory for trace output files.").String,
				Optional:            true,
			},
			"report_multiple_errors": schema.BoolAttribute{
				MarkdownDescription: helpers.NewAttributeDescription("Report multiple errors.").String,
				Optional:            true,
			},
		},
	}
}

func (r *GlobalSettingsResource) Configure(_ context.Context, req resource.ConfigureRequest, _ *resource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}

	r.clients = req.ProviderData.(map[string]*restconf.Client)
}

func (r *GlobalSettingsResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var plan GlobalSettings

	// Read plan
	diags := req.Plan.Get(ctx, &plan)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}

	if _, ok := r.clients[plan.Instance.ValueString()]; !ok {
		resp.Diagnostics.AddAttributeError(path.Root("instance"), "Invalid instance", fmt.Sprintf("Instance '%s' does not exist in provider configuration.", plan.Instance.ValueString()))
		return
	}

	tflog.Debug(ctx, fmt.Sprintf("%s: Beginning Create", plan.getPath()))

	// Create object
	body := plan.toBody(ctx)

	emptyLeafsDelete := plan.getEmptyLeafsDelete(ctx)
	tflog.Debug(ctx, fmt.Sprintf("List of empty leafs to delete: %+v", emptyLeafsDelete))

	if YangPatch {
		edits := []restconf.YangPatchEdit{restconf.NewYangPatchEdit("merge", plan.getPath(), restconf.Body{Str: body})}
		for _, i := range emptyLeafsDelete {
			edits = append(edits, restconf.NewYangPatchEdit("remove", i, restconf.Body{}))
		}
		_, err := r.clients[plan.Instance.ValueString()].YangPatchData("", "1", "", edits)
		if err != nil {
			resp.Diagnostics.AddError("Client Error", fmt.Sprintf("Failed to configure object, got error: %s", err))
			return
		}
	} else {
		res, err := r.clients[plan.Instance.ValueString()].PatchData(plan.getPathShort(), body)
		if len(res.Errors.Error) > 0 && res.Errors.Error[0].ErrorMessage == "patch to a nonexistent resource" {
			_, err = r.clients[plan.Instance.ValueString()].PutData(plan.getPath(), body)
		}
		if err != nil {
			resp.Diagnostics.AddError("Client Error", fmt.Sprintf("Failed to configure object (PATCH), got error: %s", err))
			return
		}
		for _, i := range emptyLeafsDelete {
			res, err := r.clients[plan.Instance.ValueString()].DeleteData(i)
			if err != nil && res.StatusCode != 404 {
				resp.Diagnostics.AddError("Client Error", fmt.Sprintf("Failed to delete object, got error: %s", err))
				return
			}
		}
	}

	plan.Id = types.StringValue(plan.getPath())

	tflog.Debug(ctx, fmt.Sprintf("%s: Create finished successfully", plan.getPath()))

	diags = resp.State.Set(ctx, &plan)
	resp.Diagnostics.Append(diags...)
}

func (r *GlobalSettingsResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var state GlobalSettings

	// Read state
	diags := req.State.Get(ctx, &state)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}

	if _, ok := r.clients[state.Instance.ValueString()]; !ok {
		resp.Diagnostics.AddAttributeError(path.Root("instance"), "Invalid instance", fmt.Sprintf("Instance '%s' does not exist in provider configuration.", state.Instance.ValueString()))
		return
	}

	tflog.Debug(ctx, fmt.Sprintf("%s: Beginning Read", state.Id.ValueString()))

	res, err := r.clients[state.Instance.ValueString()].GetData(state.Id.ValueString(), restconf.Query("content", "config"))
	if res.StatusCode == 404 {
		state = GlobalSettings{Instance: state.Instance, Id: state.Id}
	} else {
		if err != nil {
			resp.Diagnostics.AddError("Client Error", fmt.Sprintf("Failed to retrieve object, got error: %s", err))
			return
		}

		state.updateFromBody(ctx, res.Res)
	}

	tflog.Debug(ctx, fmt.Sprintf("%s: Read finished successfully", state.Id.ValueString()))

	diags = resp.State.Set(ctx, &state)
	resp.Diagnostics.Append(diags...)
}

func (r *GlobalSettingsResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var plan, state GlobalSettings

	// Read plan
	diags := req.Plan.Get(ctx, &plan)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}

	// Read state
	diags = req.State.Get(ctx, &state)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}

	if _, ok := r.clients[plan.Instance.ValueString()]; !ok {
		resp.Diagnostics.AddAttributeError(path.Root("instance"), "Invalid instance", fmt.Sprintf("Instance '%s' does not exist in provider configuration.", plan.Instance.ValueString()))
		return
	}

	tflog.Debug(ctx, fmt.Sprintf("%s: Beginning Update", plan.Id.ValueString()))

	body := plan.toBody(ctx)

	deletedListItems := plan.getDeletedListItems(ctx, state)
	tflog.Debug(ctx, fmt.Sprintf("List items to delete: %+v", deletedListItems))

	emptyLeafsDelete := plan.getEmptyLeafsDelete(ctx)
	tflog.Debug(ctx, fmt.Sprintf("List of empty leafs to delete: %+v", emptyLeafsDelete))

	if YangPatch {
		edits := []restconf.YangPatchEdit{restconf.NewYangPatchEdit("merge", plan.getPath(), restconf.Body{Str: body})}
		for _, i := range deletedListItems {
			edits = append(edits, restconf.NewYangPatchEdit("remove", i, restconf.Body{}))
		}
		for _, i := range emptyLeafsDelete {
			edits = append(edits, restconf.NewYangPatchEdit("remove", i, restconf.Body{}))
		}
		_, err := r.clients[plan.Instance.ValueString()].YangPatchData("", "1", "", edits)
		if err != nil {
			resp.Diagnostics.AddError("Client Error", fmt.Sprintf("Failed to update object, got error: %s", err))
			return
		}
	} else {
		res, err := r.clients[plan.Instance.ValueString()].PatchData(plan.getPathShort(), body)
		if len(res.Errors.Error) > 0 && res.Errors.Error[0].ErrorMessage == "patch to a nonexistent resource" {
			_, err = r.clients[plan.Instance.ValueString()].PutData(plan.getPath(), body)
		}
		if err != nil {
			resp.Diagnostics.AddError("Client Error", fmt.Sprintf("Failed to configure object (PATCH), got error: %s", err))
			return
		}
		for _, i := range deletedListItems {
			res, err := r.clients[state.Instance.ValueString()].DeleteData(i)
			if err != nil && res.StatusCode != 404 {
				resp.Diagnostics.AddError("Client Error", fmt.Sprintf("Failed to delete object, got error: %s", err))
				return
			}
		}
		for _, i := range emptyLeafsDelete {
			res, err := r.clients[plan.Instance.ValueString()].DeleteData(i)
			if err != nil && res.StatusCode != 404 {
				resp.Diagnostics.AddError("Client Error", fmt.Sprintf("Failed to delete object, got error: %s", err))
				return
			}
		}
	}

	tflog.Debug(ctx, fmt.Sprintf("%s: Update finished successfully", plan.Id.ValueString()))

	diags = resp.State.Set(ctx, &plan)
	resp.Diagnostics.Append(diags...)
}

func (r *GlobalSettingsResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	var state GlobalSettings

	// Read state
	diags := req.State.Get(ctx, &state)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}

	if _, ok := r.clients[state.Instance.ValueString()]; !ok {
		resp.Diagnostics.AddAttributeError(path.Root("instance"), "Invalid instance", fmt.Sprintf("Instance '%s' does not exist in provider configuration.", state.Instance.ValueString()))
		return
	}

	tflog.Debug(ctx, fmt.Sprintf("%s: Beginning Delete", state.Id.ValueString()))
	deleteMode := "attributes"

	if deleteMode == "all" {
		res, err := r.clients[state.Instance.ValueString()].DeleteData(state.Id.ValueString())
		if err != nil && res.StatusCode != 404 && res.StatusCode != 400 {
			resp.Diagnostics.AddError("Client Error", fmt.Sprintf("Failed to delete object, got error: %s", err))
			return
		}
	} else {
		deletePaths := state.getDeletePaths(ctx)
		tflog.Debug(ctx, fmt.Sprintf("Paths to delete: %+v", deletePaths))

		if YangPatch {
			edits := []restconf.YangPatchEdit{}
			for _, i := range deletePaths {
				edits = append(edits, restconf.NewYangPatchEdit("remove", i, restconf.Body{}))
			}
			_, err := r.clients[state.Instance.ValueString()].YangPatchData("", "1", "", edits)
			if err != nil {
				resp.Diagnostics.AddError("Client Error", fmt.Sprintf("Failed to delete object, got error: %s", err))
				return
			}
		} else {
			for _, i := range deletePaths {
				res, err := r.clients[state.Instance.ValueString()].DeleteData(i)
				if err != nil && res.StatusCode != 404 {
					resp.Diagnostics.AddError("Client Error", fmt.Sprintf("Failed to delete object, got error: %s", err))
					return
				}
			}
		}
	}

	tflog.Debug(ctx, fmt.Sprintf("%s: Delete finished successfully", state.Id.ValueString()))

	resp.State.RemoveResource(ctx)
}

func (r *GlobalSettingsResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	resource.ImportStatePassthroughID(ctx, path.Root("id"), req, resp)
}
